### ISSUE TITLE
hallhatatlan archívum

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#160]
A 2010 április 1-e előtti adásoknál ne rakja ki a lejátszás linket az archívumba.

Hisz úgysincsenek ott az archívumban azok afelvételek.
MÉG NINCS: https://tilos.hu/archive/2010/03/31
MÁR VAN: https://tilos.hu/archive/2010/04/01

**Comment by elek** [comment]
Gyors fixként meg lehetne csinálni, hogy ne lehessen hátrább lapozni

**Comment by szabidu** [comment]
az is jó ötlet!

**Comment by rudywaltz** [comment]
Levettem a gombot, a régébbi adásoknál (lpaozás maradt), de még lehet probléma az adásnapló oldalon: https://tilos.hu/episode/vostock/2010/03/31
generálisabb megoldás kell késöbb, hogy visszajöjjön a backandről hogy az adott file nem létezik
