### ISSUE TITLE
Éjfélen átívelő műsorok kezdete és vége

### ISSUE THREAD

**Issue by intonarumori** [tilosradio/web2#177]
Egyelőre egy ilyenről tudok, ami a Hotel North Pole.

Ez az a nap amikor ők az utolsók:
https://tilos.hu/api/v0/episode?start=1415142000&end=1415228400

Itt a kezdet és vég: 1415224800, 1415228400

Ez pedig a következő nap amikor az elsők:
https://tilos.hu/api/v0/episode?start=1415228400&end=1415314800

Itt a kezdet és vég: 1415228400, 1415232000

Az világos, hogy most úgy van megcsinálva, hogy a paraméterként átadott timestampeknél megvágja az időintervallumot.

Viszont nem az lenne a tiszta logikailag, hogy itt minden műsor ami belelóg a paramétekben leadott intervallumba, az a tényleges kezdés és vég timestamppel szerepeljen?

**Comment by rudywaltz** [comment]
duplicate #178
