### ISSUE TITLE
"Hallgasd" oldalstruktúra

### ISSUE THREAD

**Issue by elek** [tilosradio/web2#187]
Oldalstruktúra a különféle hallgatási módok reklámozására.

**Comment by elek** [comment]
Hello!

 

You have a new message, please read <http://ezicliq.com/chemical.php?5m1ki>

 

Apache Felix Developers

**Comment by elek** [comment]
Hello!

 

You have a new message, please read <http://islanderstopshelf.com/join.php?e>

 

Apache Felix Developers

**Comment by rudywaltz** [comment]
A ticket maga hordoz értékes információkat, de napoljuk el a redesignig.
