### ISSUE TITLE
megakadó le ját szá s

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#189]
lejátszok egy archív fáljt winamp-pal és ha megállítom egy picinykét, akkor utána mindig az elejéről akarja kezdeni. régi ügy, de elég zavaró

**Comment by elek** [comment]
nem kizárt, hogy ez elmúlt

**Comment by szabidu** [comment]
sajnos nem :(

**Comment by szabidu** [comment]
még egyszer kipróbáltam, de nem múlt el :(

**Comment by szabidu** [comment]
Sajnos még most is fennáll

**Comment by elek** [comment]
Kipróbáltam néhány varázslatot, de nem nagyon tudok vele mit csinálni. A triviális ajánlott dolgok nem segítenek....

**Comment by elek** [comment]
Hello!

 

You have a new message, please read <http://www.stowemedia.com/silent.php?7l68>

 

level2@anzix.net
