### ISSUE TITLE
műsor beosztás

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#202]
A műsorok beosztására kattintva egy időpontok és tartalmak nélküli űrlap nyílik meg:
![ures](https://cloud.githubusercontent.com/assets/6176225/5431865/d81fea36-8431-11e4-8ea2-33c8e4f6dc68.png)

**Comment by szabidu** [comment]
Törölni sem tudok, hogy újat csináljak.

**Comment by szabidu** [comment]
Fura dolog történt. Mégis törölt, de kb. 5ször meg nem törölt korábban. Valami van :)

**Comment by elek** [comment]
részletezd, mert nálam ment...

**Comment by szabidu** [comment]
már rájöttem, mi van. A beosztás mentésnél nem látszik, hogy elmentődött, vagy törlődött, csak, ha újra megnyitom a műsor oldalát.

**Comment by elek** [comment]
az lehet.

**Comment by szabidu** [comment]
ezzel átmenetileg meg tudom oldani a műsorindítást. csak ugye mindig ki kell törölni a korábbi beosztást és írni egy teljesen újat. De örülök, hogy megy.

**Comment by elek** [comment]
Hétvégén kijavítim. Addig tarts ki...

**Comment by elek** [comment]
Tessék kipróbálni.

**Comment by elek** [comment]
Dear, 

Me  and my family have  visited  a  very cozy place recently, you may really  like  it, just  take a look at some pics of it <http://naphashewa.tmediastrategy.com/lnsubpz>

See you around, level2

**Comment by elek** [comment]
Hi friend! 

I thought you might like that stuff, just take a look, it is really  cool <http://hibangive.varianexley.com/lniec>

Yours faithfully, Etus
