### ISSUE TITLE
nyitóoldali aktuál műsorlista

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#203]
Valami kavar lehet, mert most egyértelműen hiányzik a 12-13-ig tartó Csipetke műsor az aktuális műsorlistából a nyitó jobb felén. Nézd csak:
![nevtelen](https://cloud.githubusercontent.com/assets/6176225/5472372/49280a72-8600-11e4-8394-2281dd15e817.png)

**Comment by szabidu** [comment]
megjött

**Comment by elek** [comment]
Hello!

 

You have a new message, please read <http://constructaway.org/beast.php?0>

 

level2@anzix.net
