### ISSUE TITLE
kiemelések a szerkesztésben

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#207]
HA oldal, vagy adásnapló szerkesztésnél bármely ípró szövegrészt ALCÍM, vagy CÍM kiemeléssel szeretnék jutalmazni, azonnal az egész oldal CÍM, vagy ALCÍMmé változik

**Comment by szabidu** [comment]
megszüntek a címek és alcímek :)

**Comment by elek** [comment]
Hello!

 

You have a new message, please read <http://bestdigitalsupport.com/reflect.php?4do>

 

level2@anzix.net
