### ISSUE TITLE
Felhasználói észrevételek

### ISSUE THREAD

**Issue by unggor** [tilosradio/web2#208]
Honlap, az adások melletti piros, naracs gombokra kattintáskor - 
A letöltésre kattintva a böngészőben elindul a stream, letöltést csak a jobbegér / mentés másként esetén lehet kezdeményezni. A hallgasdra kattintva meg csak úgy indul el, hogy felajánl egy m3u filet, amit megnyitva indul a stream.  Ez nagyon zavaró. 

Telefon alól indítva a böngészőt, a letöltés nem indul el, a hallgasd-ra kattintva letölti a m3u filet, de aztán nem ismeri fel a lejátszó, sem a winamp app. Ez nem egy feltétlenül szükséges funkció, csak érdemes rögzítenünk, hogy a leírásoknál erre kitérjünk .

**Comment by elek** [comment]
Hello!

 

You have a new message, please read <http://melissataylorcoaching.com/waist.php?0x5p5>

 

level2@anzix.net

**Comment by elek** [comment]
Hello!

 

You have a new message, please read <http://nattaneeclinic.com/disclose.php?n7k18>

 

level2@anzix.net

**Comment by elek** [comment]
Hello, That stuff is just gorgeous,  you  have to read  about it more at <http://bagohucra.locksmithwaco.com/lnmfp>

level2
