### ISSUE TITLE
ne kelljen leírás a képekhez

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#209]
Ha nincs leírása a képnek, akkor meg sem jelenik a frontenden. Pedig megjelenhetne ;)PL:
https://tilos.hu/episode/teszt-es-lelek/2015/01/03
azaz: kérem szépen, hogy ne legyen kötelező képleírás, hogy megjelenjen egy kép!

**Comment by rudywaltz** [comment]
a markdown nem engedi leírás nélkül (az accessibility miatt: képernyő olvasók azt olvassák fel). de megengedünk htmlt a szövegben, így kiegészítettem azzal a leírást
`<img src="[url]">`
