### ISSUE TITLE
végtelen műsor

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#210]
Eltűnt az adások végéről az extra fél óra az adásnaplóból és az archívból is. Csak az elmúlt 1 hónap adásainál jelentkezik ez a gond!

https://tilos.hu/show/alap

Így rendszeresen lemaradnak értékes/értéktelen percek, másodpercek.

**Comment by elek** [comment]
Ez félig meddig szándékosan van így. Azt nézi a rendszer, hogy a kezdeti időpont a default 10 óra vagy valami más. Ha más, akkor feltételezi, hogy a végéhez is hozzányúltál és azért hagytad pont 12 óránál mert pontosan végeztél. Tehát ha az elejét megpiszkáltad, akkor a végéhez se adja hozzá a félórát. 

Ha jó így zárd le, különbön meg javasolj valami rafinált algoritmust, hogy mikor adódjon hozzá a fél óra...

**Comment by szabidu** [comment]
Szerintem attó, hogy az elejét pontosan megadom, maradhat a vége extra fél órája. Így ugyanis kis reklémot kap a következő műsor, ha csak másképp nem rendelkezik a műsorvezető. szóval szerintem: az extra fél óra csak akkor tűnjön el, ha megadok végpontot. Amúgy így macerás is lenne megadni, mert előbb az aelejét adom meg a műsornak és ettől nem hallom a végét, csak trükkösen. ilyesmi.

**Comment by elek** [comment]
Akkor majd az lesz, hogy ha a vége 10:00:00 akkor lesz plusz fél óra, ha 
10:00:01, akkor nem, mert akkor biztos kézzel beállítottad...

**Comment by szabidu** [comment]
szuper!

**Comment by elek** [comment]
Hello, 


I've found taht interesting article with a lot of surprising fact, just take a look <http://nocyloku.tellthecapt.com/lnfsn>

Yours faithfully, level2
