### ISSUE TITLE
nem szerkeszthető személyes oldalak

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#211]
A szemelyes profilt sajnos nem sikerül módosítani se nekem, se Daninak. Meg tudod nézni mi lehet az oka? Nem jelenik meg szerkesztesi opció.
Köszi
Renocs

**Comment by elek** [comment]
Elvileg javítva, kéretik tesztelni.

Bár itt még a régi típusú szerkesztő van.

**Comment by szabidu** [comment]
nekem megy, akkor náluk is menni kék

**Comment by elek** [comment]
Hello!

 

You have a new message, please read <http://marathiclick.com/speed.php?p2u3>

 

level2@anzix.net

**Comment by elek** [comment]
Hello!

 

You have a new message, please read <http://www.windows10tipss.com/across.php?f2>

 

level2@anzix.net

**Comment by elek** [comment]
Hey friend, 

I've had a crazy  day yesterday  and I wanted to share some the  story of it with you, you can find it here <http://strategy.jesusoursavior.info/lnxxbk>

See you around, level2
