### ISSUE TITLE
admin login porbléma

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#212]
Az alábbi felhasználók jelezték, hogy hiába adnak meg új jelszót, nem engedi be őket a rendszer:

**Comment by elek** [comment]
Az adott email címek közül 7 nél találtam hibát, párnál viszont azt 
láttam, hogy még soha nem kértek jelszó emlékeztetőt. A 7et javítottam, 
a többieknél szerintem mennie kellene.

**Comment by szabidu** [comment]
Azért nem kértek, mert szóltam nekik, hogy csak akkor kérjenek, ha megjavult. Köszi Marci! Írok is nekik!

**Comment by szabidu** [comment]
Vályi: Nagyon fura. Login után egy villanásra felvillan az admin oldal (kék hasábbal balra), de azonnal betölti a tilos.hu-t, amin ugyan kint van, hogy be vagyok jelentkezve, de semmilyen szerkesztési lehetőséget nem nyújt, csak ugyanazt az oldalt látom, amit látogatóként. (Chrome,Firefox)
 
Safariban a login utan kijon a kek oldalpanel balra, de kozepen ujra ott a login ablak, amibe beirva a logint es a pw-t betolti a sztenderd tilos oldalt, ahogy fent, szerkesztesi lehetosegek nelkul. 
![screen shot 2015-01-07 at 23 31 49](https://cloud.githubusercontent.com/assets/6176225/5658724/290d4b5e-9707-11e4-8dbc-1180f03f9df8.png)
![screen shot 2015-01-07 at 23 31 05](https://cloud.githubusercontent.com/assets/6176225/5658725/2ab56554-9707-11e4-9dd1-1b61fee2cec4.png)

**Comment by szabidu** [comment]
már többen jelezték, hogy sikerült belépniük. Fuck yeah!
