### ISSUE TITLE
nem megy a linkbeillesztés/csere

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#213]
pedig nagyon sokan kérik

**Comment by elek** [comment]
Mi nem megy? Hol? Adásnaplóban?

**Comment by szabidu** [comment]
oh, elég pongyola voltam :)
a műsorokhoz csatolt linkek (face, page ilyesmi)

**Comment by elek** [comment]
Na de azok remekül mennek. Legalábbis nekem, előbb kipróblátam...

**Comment by szabidu** [comment]
Nálam nem látszik a link hozzáadás, de a korábban a műsorhoz tartozó link sem
![3utas](https://cloud.githubusercontent.com/assets/6176225/5696026/b1b5f8bc-99bd-11e4-8e52-a22b7f0dd7ff.jpg)

**Comment by elek** [comment]
Az adminnal nem megy, de a műsorkészítőkkel megy. Elismerem nem szép, 
majd az adminnal is menni fog.

**Comment by szabidu** [comment]
óhhh! ez bőven elég mostra.

**Comment by elek** [comment]
Hello!

 

You have a new message, please read <http://ecommercetransition.com/involve.php?uq>

 

level2@anzix.net

**Comment by elek** [comment]
Hello!

 

You have a new message, please read <http://kchiryou.net/seem.php?u>

 

level2@anzix.net
