### ISSUE TITLE
egy irányba rossz a link - Magic Monday zavarok

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#215]
Ha egy Magic Monday műsorkészítő oldalárónak középső oszlopában ráklikkelek a "műsorai" alatti Magic Monday linkre, akkor erre az oldalra küld:
https://tilos.hu/show/mm
pedig a műsor oldal ez:
https://tilos.hu/show/Magic

Hiába próbálom a műsor aliast (Monday) megváltoztatni (monday), mentéskor semmi nem történik :(
Pedig azt gyanítom, hogy a nagy kezdőbetű okozza.

**Comment by elek** [comment]
A műsor alias megváltoztatása egyelőre nem támogatott. Ideális esetben nem is szabadna látni a mezőt, hogy megváltoztatható.

Mivel az alias technikailag két helyre is mentődik a műsorkészítőhöz és a műsorhoz is. Ha megváltoztatujuk a műsor aliasát pont ez lesz mint itt.

Javítható azzal, ha a contributurokat törlöd és felveszed újra (ezt most megtettem).

**Comment by szabidu** [comment]
Ez csak olyan esetben problémás, hogyha rossz aliast adok meg. pl van egy Anikó műsorkészítőnk, aki a hosszú ó miatt szív és nem tudom megváltoztatni, se törölni.

**Comment by elek** [comment]
Hello!

 

You have a new message, please read <http://integritybpo.com/uniform.php?6e2e>

 

level2@anzix.net
