### ISSUE TITLE
face like és megosztás műsorra

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#217]
A műsoroldalaknál korábban volt face like. Jó lenne visszahozni valahova felülre. Mondjuk a műsor címével egy sorba.

**Comment by gpetra** [comment]
igen, a cím mellé kellene valahogy, egyelőre nekem sincs jobb ötletem

2015-01-15 11:53 GMT+01:00 szabidu <notifications@github.com>:

**Comment by schaggie** [comment]
Bocsi, de úgy emlékszem a face 'share' gombot szeretnénk ide, nem csak 'like'-ot. Vagy nem jól emlékszem?

**Comment by szabidu** [comment]
Jól emlékszel Ági, ezért is az issue címe: face like és megosztás műsorra

**Comment by elek** [comment]
Hello!

 

You have a new message, please read <http://scannerlab.com/powerful.php?2hs>

 

level2@anzix.net
