### ISSUE TITLE
face like és megosztás adásnaplóba

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#218]
Jó lenne valahova felülre. Mondjuk a hallgat-letölt páros elé.

**Comment by gpetra** [comment]
igen, ott remek lenne egy jó kis facebook-kékkel

2015-01-15 11:55 GMT+01:00 szabidu <notifications@github.com>:

**Comment by elek** [comment]
Én nem terhelném még több gombbal azt a vidéket. Inkább felraknám a jobb 
felső sarokba a sidebar tetejére valami keretezetteb helyre.

De majd csinálok valamit, hogy látszon, hogy hogy gondolom...

**Comment by elek** [comment]
Hello!

 

You have a new message, please read <http://seniorcitizen.co.za/else.php?r6>

 

level2@anzix.net
