### ISSUE TITLE
admin időszakos optimalizáció

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#219]
Marci! levennéd ezeket az egyszerű felhasználok adminfelületének bal oldaláról:
TILOS tartalom
Műsorok
Műsorkészítők
Mixek
Oldalak
Hírek
Admin hírek
Hozzászólások

Most ugyanis klikkelgetnek, de semmi nem megy. Viszont, ha már megy valami és AKKOR megjelennek újra a linkek, akkor lesz jelentősége és könnyebbb is lesz észrevenni (mert előtte nem látszott)

**Comment by elek** [comment]
Egyszer már volt ilyen issue, és akkor megegyeztünk, hogy nem baj hogy 
látják. A műsorok, műsorkészítők, mixek odalak, admin hírek ráadásul 
megy is. Csak a hírek és hozzászólások nem.

De amúgy levehetem majd. Vagy ami általános információ (mix/műsorok) azt 
is lejjeb rakhatom egy admin blokkba és a hozzászólásokat meg addig 
elbújtatom...

m.

**Comment by szabidu** [comment]
Megcsináltam a megbeszélt sorrendet, már csak azt kéne hozzátenni, hogy egyszerű felhasználó ne lássa az oldalak, hirek, admin hírek részt.

**Comment by elek** [comment]
Dear friend! 

There are a couple of books that inspire  me to do really great things, here is the list of that books <http://story.poulter7.com/lnifths>

Very truly yours, level2
