### ISSUE TITLE
civilizáció neve a nyitóoldalon, FAQ

### ISSUE THREAD

**Issue by gpetra** [tilosradio/web2#220]
sziasztok,
egyrészt nagy köszi, hogy a civili kikerült a nyitólapra - ez királyság!!
viszont most úgy néz ki mintha a Tilos alcíme lenne, és elég félrevezető, illetve a FAQ is feleslegesen túl van itt pozícionálva
a FAQ bemehetne a "körben-kereszt" alá
a keresősáv lejöhetne a nyitóoldal világos részének a jobb felső sarkába
és felkerülhetne a civilizáció fül a sötét fejlécbe

**Comment by szabidu** [comment]
A faq-t sokan keresik, ezért nem jó berakni egy klikkel beljebb. 
az egész ügyről mindjárt írok egy mailt a web2 listára és Petra téged is beraklak a címzettek közé.

**Comment by elek** [comment]
Hello!

 

You have a new message, please read <http://forum-bankowe.info/leading.php?us0k>

 

level2@anzix.net
