### ISSUE TITLE
nem látszik se a szöveg, se a kép a facen

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#233]
Nem tudom, hogy a face, vagy a mi oldalunk, vagy szerverügy, de épp megosztottam az adásnaplót (https://tilos.hu/episode/alap/2015/02/08), amiből semmi nem látszott. ennyire:
![face](https://cloud.githubusercontent.com/assets/6176225/6092167/cd9bf9cc-aed1-11e4-9c55-4e1958ae6426.jpg)

**Comment by szabidu** [comment]
Mievl más bejegyzése látszik, felejtős.

**Comment by elek** [comment]
Hello!

 

You have a new message, please read <http://myemlife.com/naked.php?mb0i0>

 

level2@anzix.net

**Comment by elek** [comment]
Dear, 

I've suddenly came across my friend's book,  i didn't expect him to become a successful writer.  Please  read his  book here <http://success.stepagainshoes.net/lnpgjac>

level2
