### ISSUE TITLE
Nem megy az rss

### ISSUE THREAD

**Issue by rudywaltz** [tilosradio/web2#234]
Nem tudom gépről ellenőrizni de az androidps podcast kezelőm ezt mondja
```
Failed Feeds
HalAdó - Rabol a balin [Tilos Rádió podcast]
Reason to fail: SocketTimeoutException
Haza és haladás [Tilos Rádió podcast]
Reason to fail: SocketTimeoutException
Irodalmi lépegető [Tilos Rádió podcast]
Reason to fail: SSLPeerUnverifiedException - No peer certificate
Kelta karó [Tilos Rádió podcast]
Reason to fail: SSLPeerUnverifiedException - No peer certificate
Kovács Ádám Hangpostája [Tilos Rádió podcast]
Reason to fail: SocketTimeoutException
Régen minden jobb volt! [Tilos Rádió podcast]
Reason to fail: SocketTimeoutException
```

**Comment by szabidu** [comment]
hw hiba miatt semmi nem ment. este újfent alaplapot cserélnek a
szerverben a rackforestnél. 

lezárom. 

szabi 

---
tel: +36 30 263 2304

http://raga.hu
Tilos Radio - http://tilos.hu - 90.3 Fm - Budapest

2015-02-09 07:56 időpontban David Barkóczi ezt írta: 

> Nem tudom gépről ellenőrizni de az androidps podcast kezelőm ezt mondja 
> 
> Failed Feeds
> HalAdó - Rabol a balin [Tilos Rádió podcast]
> Reason to fail: SocketTimeoutException
> Haza és haladás [Tilos Rádió podcast]
> Reason to fail: SocketTimeoutException
> Irodalmi lépegető [Tilos Rádió podcast]
> Reason to fail: SSLPeerUnverifiedException - No peer certificate
> Kelta karó [Tilos Rádió podcast]
> Reason to fail: SSLPeerUnverifiedException - No peer certificate
> Kovács Ádám Hangpostája [Tilos Rádió podcast]
> Reason to fail: SocketTimeoutException
> Régen minden jobb volt! [Tilos Rádió podcast]
> Reason to fail: SocketTimeoutException
> 
> --
> Reply to this email directly or view it on GitHub [1].
 

Links:
------
[1] https://github.com/tilosradio/web2/issues/234

**Comment by szabidu** [comment]
hw hiba volt
