### ISSUE TITLE
teljesen összekavarodott az időzítés felvitele

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#238]
A tandori italiano és a tandoori salami helyet cserélt az év elején. Amikor ezt fel akartam vinni a táblába, akkor kiderült, hogy nem kezeli jól a rendszer az időzítéseket.
1. néha nem jelenik meg semmi, ha az időzítés szerkesztése funkcióra bökök 
2. ha mégis megjelenik az időzítés szerkesztése, akkor viszont csak az ELSŐ időzítés jelenik meg, bármelyik időzítést is akarom szerkeszteni. Ezekhez a műsorokhoz már van 3 különféle időzítés, de emiatt csak a legelső szerkeszthető.
Meg tudom csinálni a dolgomat, ha minden időzítést kitörlök és egyenként újra felviszem őket az új adatokkal, de nem a legpraktikusabb.

**Comment by szabidu** [comment]
Sem törölni, sem javítani nem tudom az időzítéseket és most 9 új időzítést kéne felvinnem :(((

**Comment by elek** [comment]
Hello!

 

You have a new message, please read <http://www.gazzaz.com.sa/neither.php?gy>

 

level2@anzix.net
