### ISSUE TITLE
eltűntek a + fél órák

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#240]
Se a lejátszásnál, se a letöltésnél nioncs meg a plusz egy feles az archívban és ezért az adásnapló oldalnál sem. Ugyancsak hiányzik a podcastból :(

**Comment by szabidu** [comment]
Lezártam, mert a Haza és haladásnál megtaláltam a + fél órát, de kicsit később a Konturnál meg nem.
H und H: https://tilos.hu/mp3/tilos-20150306-080000-103000.mp3
Kontour: https://tilos.hu/mp3/tilos-20150302-163000-183000.mp3

**Comment by elek** [comment]
Hello!

 

You have a new message, please read <http://test.agape.org/specify.php?ghg>

 

level2@anzix.net

**Comment by elek** [comment]
Hey! 

Just take  a look at that crazy stuff, I'm slightly  shocked! Here it is <http://surprise.panuwit.com/lnijjz>

level2
