### ISSUE TITLE
SocialCtrl hiba

### ISSUE THREAD

**Issue by rudywaltz** [tilosradio/web2#247]
Az éles kódban is ezt írja a konzol.
`Error: [ng:areq] Argument 'SocialCtrl' is not a function, got undefined`

Nálam a fejlesztői környezet is furán viselkedik, folyton reloadolja az oldalt a `gulp server` parancs után (de lehet hogy csak az én készülékemben van a hiba)

**Comment by elek** [comment]
SocialCtrl elvileg kiirvta. gupl server helyett szerintem egyszerűbb egy gulp watch + nginx, mert azzal nem lesz minden féle Cross Origin Request Policy probléma, ha az aktuális szervert használod. Ha kell leírom, hogy megy...
