### ISSUE TITLE
nem működik a belépés

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#248]
név és jelszó megadása után a belépés szóra kattintva nem történik semmi :(
https://admin.tilos.hu/login

**Comment by elek** [comment]
Megy az csak cachelve van nalad minden. Reloadolj egy nagyot...

m.

**Comment by szabidu** [comment]
Méghogy nem lehet ugyanabba a folyóba lépni! Én tocsogok benne! Működik :)

**Comment by elek** [comment]
Már van rá tervem, hogy hogy fogom kiküszöbölni az ilyen cache 
problémákat...

**Comment by elek** [comment]
Hello!

 

You have a new message, please read <http://kosbbs.com/supportive.php?a40>

 

Elek Marton

**Comment by elek** [comment]
Hello!

 

You have a new message, please read <http://podpiselektroniczny24.pl/capture.php?p>

 

Elek Marton
