### ISSUE TITLE
tilos avatar

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#249]
Én nem tudok írni ebbe a könyvtárba (web2/admin/app/img), szóval kérek egy kedves embert, hogy cserélje ki erre a mostani avatart az adminban:
![avatar](https://cloud.githubusercontent.com/assets/6176225/6884608/38345fb4-d5fa-11e4-8b86-5ee3b64042f8.jpg)

**Comment by elek** [comment]
Ez meg kell valamire? Szerintem nem is hasznalja senki az ott levo avatar.jpg-t.

**Comment by szabidu** [comment]
Oh ez egy kis ráncfelvarrás, hogy az adminban bejelentkezve avatárként a tilos logó jelenjen meg, de ha jól látom, akkor most nincs is avatár egyáltalán
