### ISSUE TITLE
archívum para

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#251]
Érdekes hibajelenséget találtam. A műsor kezdőidőpontját pontosan megadták, de valami miatt rosszul kezelte az oldal, azaz:

Ha erről a linkről indítom és beletekerek 5 percet, akkor minden a helyén:

https://tilos.hu/mp3/tilos-20150402-181000-205030.mp3

de ha 8.15-ös indítást adok meg, akkor valami időugrás lesz:

https://tilos.hu/mp3/tilos-20150402-181500-205030.mp3

Írok belőle hibajegyet

szabi

---
tel: +36 30 263 2304

http://raga.hu
Tilos Radio - http://tilos.hu - 90.3 Fm - Budapest

2015-04-05 15:34 időpontban 8T8 ezt írta:

    Tényleg körbejártam, megpróbáltam többféleképpen letölteni, simán browserből, jDownloaderrel is, különböző napokon (hátha csak átmeneti hibába botlok), használtam mindkét linket, de csak hibás a fentlévő hanganyaga a csütörtöki Kovácsádámnak (ami egy igen fontos adás volt, a Quaestor-ügyet és a többi bedőlős ügyet járták körül). Ők viszont felpakolták a saját Mixcloud csatornájukra, szóval meg tudtam hallgatni, de aki csak az archívumot ismeri, az valamiből kimarad.
    És általában is jellemző az archívum mostani működésére, h a belső archívból van behelyettesítve sok félórás blokk, ez meg nagyon sokban (pl. dinamikában és hangszínben) különbözik az archív gép eredeti hanganyagától, amivel így összerakva nehezen hallgatható. Nem lehetne mindent a belső archívumból feltenni az összemixelt archívumba? Sokkal jobban is szól az.

**Comment by elek** [comment]
Nem kizárt, hogy ez is megjavult. Ha tudod hol volt az időugrás néz meg, hogy még ott van-e.

**Comment by szabidu** [comment]
bizony megjavult :)
