### ISSUE TITLE
egy fél órás blokkon belül nem működik a másodperces megadás

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#253]
Ha nem nyúlik át a megadott műsorrészlet fél órás blokkon túl, akkor hibát dob a rendszer:pl:
https://tilos.hu/mp3/tilos-20141104-003746-003903.mp3

"X - A videót nem lehet lejátszani, mert a fájl sérült." - Firefox
Chrome csak nem játssza le és kész :(

átnyúlósan megadva:
https://tilos.hu/mp3/tilos-20141104-003746-010003.mp3

**Comment by elek** [comment]
teszteld, please

**Comment by szabidu** [comment]
oh, yeah!
