### ISSUE TITLE
eltűnő SELECTION  live stream link a nyitón

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#254]
Carlos küldött pár php sort ide: 
https://github.com/tilosradio/web2-frontend/edit/master/app/partials/sidebar_right.html
Persze nem működnek, mert nem php, de nagyon jó lenne, ha a hétfői muzsika CSAK AKKOR jelenne meg az oldalon, amikor aktív a tream

**Comment by elek** [comment]
A főoldalon jelenik meg, amikor aktív. Samsara szintén (ha jól lesz elnevezve a stream...).
