### ISSUE TITLE
a kereső a fejlécben nem mindig ad találatot

### ISSUE THREAD

**Issue by atomgomba** [tilosradio/web2#256]
Sem a "smokin headz", sem a "headz", sem a "smokin" kifejezésre nem ad találatot, pedig az API hívás sikeresen visszatér, de vagy üres tömböt ad vagy nincs benne a Smokin'HeadZ.

```sh
/home/kiri% curl 'https://tilos.hu/api/v1/search/query?q=smoki'
{"elements":[]}%
```

Szerintem case-insensitivnek kellene lennie és az egész sztringben keressen, esetleg lehetne fuzzy is.

**Comment by atomgomba** [comment]
A fuzzy kereséshez: most látom, h a PHP-ban alapból vannak ilyen sztringösszehasonlytó függvények:

http://php.net/manual/en/function.levenshtein.php
http://php.net/manual/en/function.similar-text.php

Persze kérdés, h ezek unicode szöveggel hogyan működnek.

**Comment by szabidu** [comment]
Már semmire nem ad találatot :(((((
