### ISSUE TITLE
archívum kavarodás és elérhetetlenség

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#259]
http://tilos.hu/archive/2014/09/04

Egyrészt valami miatt a linkek is el vannak csúszva a gombok mögött, másrészt meg akármit csináltam, egyikkel sem tudtam elérni semmit. Chrome és Firefox (legújabbak) próbálkoztam.

**Comment by szabidu** [comment]
04.25-e, szombat 22:30 utáni adások még hiányoznak.

**Comment by elek** [comment]
Hello!

 

You have a new message, please read <http://espacepiano.fr/town.php?o>

 

level2@anzix.net
