### ISSUE TITLE
Eltűnt API hívások

### ISSUE THREAD

**Issue by laszlo-karpati** [tilosradio/web2#260]
Vasárnap este óta (legalábbis azóta biztosan) nem megy az /api/v0/. Emiatt miatt az androidos alkalmazásban nem megy semmi az élő adás hallgatását leszámítva. 

Pl. a http://tilos.hu/api/v0/show

**Comment by elek** [comment]
Sajnos erre nem gondoltunk a költözéskor. Viszont a v0 api visszaállítása kb. annyi munka lenne (vagy több) amennyi alatt átírom az android alkalmazást v1-re...

**Comment by laszlo-karpati** [comment]
Ok, átírtam az alkalmazást, hogy a v1-et használja és kiadtam az új verziót (v5.5).

**Comment by elek** [comment]
Nagy király vagy. Igazából most hogy nézem a v0 már egy ideje elavult 
adatbázist használt. Tehát pl. az új műsorok hiányoztak belőle.

Szóval sokkal jobb lett. Köszi a gyors patch-et.
