### ISSUE TITLE
hirek képfeltöltés hiba

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#271]
Hiba 1.png Hiba történt a feltöltés közben. Próbálkozzunk újra. 

Minden képfeltöltésre ezt írja :(

**Comment by elek** [comment]
Odáig jutottam, hogy feltölti, de nem mutatja. Működik végül?

**Comment by szabidu** [comment]
Nem megy. Ugyanazt írja a feltöltéskor, azaz helyette: "Hiba történt a
feltöltés közben. Próbálkozzunk újra."

2015-06-08 21:53 GMT+02:00 Elek, Márton <notifications@github.com>:

> Odáig jutottam, hogy feltölti, de nem mutatja. Működik végül?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tilosradio/web2/issues/271#issuecomment-110119869>.
>



-- 
tel: +36 30 263 2304

http://raga.hu
Tilos Radio - http://tilos.hu - 90.3 Fm - Budapest
