### ISSUE TITLE
TTT

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#274]
Kéne egy, a hangtárhoz hasonló füles felület a Tilos Támogatói Tagkártyának.
a címe ez: tilos.hu/ttt
1. fül: aktuális hónap támogatott programjai
2. fül kártyaleírás
3. fül támogatók
Itt egy táblázat lenne, amiben a támogató cégek max 140 karakterben bemutatkoznak, aza a tábla oszlopai:
név, bemutatkozás, webcím(ek), logó
Talán még azt is lehetne, hogy akik 20%, vagy a feletti kedvezményt kapnak, azok az arany támogatók - kis színnel kiemelve legfelül
10-219% - ezüst támogatók - újab szín
10% alatt bronz támogató - újabb szín
4. fül prémium tartalom - ide csak jelszóval lehetne belépni, de a jelszó csak évente változna.

az egész aljára pedig kéne egy feliratkozás alevlistára opció. - mondjuk ez akár a mailto:ttt@tilos.hu?subjectfeliratkozás is megteszi :)

**Comment by elek** [comment]
a page kreálást is tesztelheted...

**Comment by szabidu** [comment]
Köszi megy az oldallétrehozás! Ez kéne az oldalakhoz:
1. fül
aktuális havi program: https://tilos.hu/page/ttt-havi
2. fül
Kártyaleírás: https://tilos.hu/page/ttt
3. fül
Támogatók/elfogadóhelyek: https://tilos.hu/page/ttt-tamogatok

Nagyon örülök, ha ebből a háromból tudsze egy füles oldalt csinálni és a ttt.tilos.hu oldalnak is a tilos.hu/ttt-re kéne mutatnia, ami a terv szerint ez az oldal lenne a mostani címén: https://tilos.hu/page/ttt

**Comment by schaggie** [comment]
Yay!! :))
