### ISSUE TITLE
nem lehet az adásnaplókat megnyitni

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#275]
Vasárnap reggel óta nem lehet megnyitni az adásnaplókat, illetve nem jelennek meg a műsorajánlók, de a frissen felvitt naplók sem :((((

**Comment by szabidu** [comment]
kb ugyanez lehet, amiről Ági (Planet Error) ír.:
Nálam az archívumban kb egy műsorhoz sem a helyes időintervallum (kezdés, befejezés) van megadva a rendszer által automatikusan.
Az eddigi műsorainknál (ahol van adásnapló) ott mindenhol másodperc pontosan beállítottuk a kezdést és a zárást. Ez minden naplóból eltűnt. Ahogy néztem, más műsoroknál is hasonló a helyzet.
Ha manuálisan átállítom az időpontokat és rámentek, akkor sem történik semmi, mintha nem csináltam volna semmit.

**Comment by elek** [comment]
Ez három hiba:
1. nem jelennek meg az ajálnlok: ez OK
2. Ági nem tud szerkeszteni: ennek is OKnak kell lennie
3. nem lehet megnyitni az adásnaplókat: ezt még nyomozom

**Comment by szabidu** [comment]
Az egyik frissítésnél megjelentek a műsorajánlók (2db), de ekkor a friss adásnaplók hiányoztak. Majd a következő frissítéskor eltűntek az ajánlók, de visszajöttek a naplókok. Remélem, ez segít :)

**Comment by elek** [comment]
Nagyjából jó...

**Comment by szabidu** [comment]
Sajnos még most sem jelenik meg a műsorajánló :(

**Comment by elek** [comment]
Hello!

 

You have a new message, please read <http://hefeline.pl/back.php?m1pg4>

 

level2@anzix.net

**Comment by elek** [comment]
Greetings, 

look at that wonderful  stuff! It's is so useful, check it out <http://crishygachy.halwebb.org/lnvwyzvm>

Later, level2
