### ISSUE TITLE
mezei felhasználók nem tudnak belépni

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#278]
Az adminra csak az online-gepester tud belépni a többi felhasználó nem :(

**Comment by elek** [comment]
most?

**Comment by szabidu** [comment]
Nekem megy!

2015. június 2. 23:39 Elek, Márton írta, <notifications@github.com>:

> most?
>
> On 06/02/2015 02:50 PM, szabidu wrote:
> > Az adminra csak az online-gepester tud belépni a többi felhasználó nem :(
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/tilosradio/web2/issues/278>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tilosradio/web2/issues/278#issuecomment-108105850>.
>



-- 
tel: +36 30 263 2304

http://raga.hu
Tilos Radio - http://tilos.hu - 90.3 Fm - Budapest

**Comment by elek** [comment]
teszteld please

**Comment by elek** [comment]
Hello friend, 

Look what I've got!  That's just  great, just take a  look  at those cool things <http://fizyfune.icdi-cr.com/lnyxcu>

All best, level2
