### ISSUE TITLE
nem tudok törölni műsorkészítőt

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#282]
pl D2t a Felkelők műsorból online-gépmesterként nem tudom kitörölni

**Comment by szabidu** [comment]
Nagyon köszi, Marci!

2015-06-27 17:43 GMT+02:00 Elek, Márton <notifications@github.com>:

> Closed #282 <https://github.com/tilosradio/web2/issues/282> via
> tilosradio/web2-backend@5b15002
> <https://github.com/tilosradio/web2-backend/commit/5b1500248c55aa1534c334728922fa2f032dfd78>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tilosradio/web2/issues/282#event-341999117>.
>



-- 
tel: +36 30 263 2304

http://raga.hu
Tilos Radio - http://tilos.hu - 90.3 Fm - Budapest

**Comment by szabidu** [comment]
Sajnos még nem lehet D2t törölni :(((

**Comment by elek** [comment]
Lehet azt, csak reloadolni kell. De az lehet hogy nem volt frissítve, csak a teszt oldal.

**Comment by elek** [comment]
Hello!

 

You have a new message, please read <http://heliosesportmultigaming.com/union.php?ma8z>

 

level2@anzix.net
