### ISSUE TITLE
felhasználóként nem lehet menteni a műsor rövid/hosszú leírását

### ISSUE THREAD

**Issue by gpetra** [tilosradio/web2#284]
Sziasztok,
Firefoxon keresztül próbáltam menteni az intro módosítását, de nem sikerült.
Nálam van gond, vagy a honlapon?
Köszi,
petra

**Comment by szabidu** [comment]
Az egyedi felhasználóknál jelentkezik a probléma. Adminból meg tudom változtatni a rövid leírást... ha arról van szó.

**Comment by gpetra** [comment]
a hosszabb leírást szeretném módosítani,képeket beszúrni, ilyesmi

2015-07-15 7:59 GMT+02:00 szabidu <notifications@github.com>:

**Comment by elek** [comment]
Hello!

 

You have a new message, please read <http://laforcesecurite.com/whole.php?9>

 

level2@anzix.net

**Comment by elek** [comment]
Hello!

 

You have a new message, please read <http://weblinetraffic.com/tale.php?yu7cz>

 

level2@anzix.net
