### ISSUE TITLE
képek középre ugrottak

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#287]
Ezért elkezdtek kicsit szétcsúszni oldalstruktúrák. Pl itt közvetlenül az adás címe előtt volt a kis "hallgatás" hangszóró:
https://tilos.hu/page/legendarium-ez-a-jovo

**Comment by reyrodrigez** [comment]
[Kivettem a `mixin`-t](https://github.com/tilosradio/web2-frontend/commit/0ded95393a4cabc4248ab40dec00d35bdc6f934c) ami középre igazított minden képet, így most a nagy képek is balra igazodnak, ezt később meggyógyítom egy flexboxxal.

**Comment by szabidu** [comment]
Ez szuper! A test oldalon azért nem látszik, mert elmúlt az automata frissítés?

**Comment by tilosradiob** [comment]
Igen. Ha szamitogep kozelben leszek deployolok...

On October 23, 2015 6:13:27 PM GMT+02:00, szabidu <notifications@github.com> wrote:
>Ez szuper! A test oldalon azért nem látszik, mert elmúlt az automata
>frissítés?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/tilosradio/web2/issues/287#issuecomment-150622014

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by elek** [comment]
Hello!

 

You have a new message, please read <http://leepak.org/despite.php?dit>

 

level2@anzix.net

**Comment by elek** [comment]
Hello!

 

You have a new message, please read <http://porterhomeimprovement.com/essence.php?w2>

 

level2@anzix.net
