### ISSUE TITLE
Firefoxban egyik színes letöltős/hallgatós link sem megy

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#289]
Firefoxban egyik színes letöltős/hallgatós link sem megy az archívban :((((

**Comment by elek** [comment]
Nálam igen (Linux/FF). Nem raktál fel valami blockert?

m.

**Comment by szabidu** [comment]
Igazad van. Az adblock zavarta. de eddig azzal is ment.. ki érti ezt?
Én!

2015-09-22 19:46 GMT+02:00 Elek, Márton <notifications@github.com>:

> Nálam igen (Linux/FF). Nem raktál fel valami blockert?
>
> m.
>
> On 09/22/2015 06:33 PM, szabidu wrote:
> > Firefoxban egyik színes letöltős/hallgatós link sem megy az archívban
> :((((
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/tilosradio/web2/issues/289>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tilosradio/web2/issues/289#issuecomment-142361268>.
>



-- 
tel: +36 30 263 2304

http://raga.hu
Tilos Radio - http://tilos.hu - 90.3 Fm - Budapest

**Comment by elek** [comment]
Hello!

 

You have a new message, please read <http://dentha.com/stroke.php?n>

 

level2@anzix.net
