### ISSUE TITLE
a hangtáras ftp feltöltés para

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#290]
a hangtáras ftp feltöltés max 200 kb sebességű (kicsit több kéne), de állandóan el is szakad a kapcsolat, ezért egy nap alatt 1 db fájlt tudtam csak feltölteni

**Comment by szabidu** [comment]
helyesbítek: nem tudok feltölteni, csak úgy tűnt, hogy tudok, de valójában nem megy fel a fájl

**Comment by elek** [comment]
Ez akkor total commanderrel ha jól értem megoldódott.

**Comment by elek** [comment]
Hello, That stuff is just gorgeous,  you  have to read  about it more at <http://bagohucra.locksmithwaco.com/lnmfp>

level2
