### ISSUE TITLE
kék linkek

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#292]
A hangtár miatt feketére lettek változtatva a linkek az oldalon, holott minden más paginán jól néz ki és jól látható, ha a linkek kékek. Vissza lehetne kapni a kék linket minden máshol-e?

**Comment by rudywaltz** [comment]
Mintha ez már működne (bár én pirosnak látom őket)

**Comment by szabidu** [comment]
tényleg! A piros is szuper! Köszi a találatot!
