### ISSUE TITLE
a nyitooldal jobb oszlopának megjelenése - BIGBAJ!

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#294]
Nagyon fontos lenne, hogy a jobb oldali oszlop beillesztett extra linkjei:

Win Phone app
android app
TTT kártyainfo
pláza

akkor is megjelenjenek, ha 1000 pxlnél szűkebb az oldal. Pl most nem látják az okostelefon használók a nyitóoldali  app linkeket.

**Comment by rudywaltz** [comment]
a 'hidden-xs' class mondja azt hogy ne látszódjon a töréspont alatt, leveszed a megfelelő divről akkor megjelenik mobilon is.
