### ISSUE TITLE
archívum hangerőmaximalizálása

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#295]
Azért hogyha egyszer megoldható lenne, hogy tiszta legyen a hang _és egyben hangos is_, az nem lenne hátrány, mert leszakad a fejem, ha bármi mást megnyitok laptopon/telóval/stb. azután, hogy Tilos-os cuccokat hallgatva felpumpálom maxra a hangerőt, hogy a közelében legyen annak, amilyen hangosan hallgatni szeretném a dolgokat. 

Szóval csak amolyan bump-ként dobtam ezt, hogy az issue életben maradhatna, hátha egyszer sikerül olyan technikai színvonalhoz eljutnunk, hogy ez is megoldható legyen, 
kösz, písz!

**Comment by szabidu** [comment]
Meg kéne tolni 6dB-et a hangerőn, annyit tuti belefér!!!

**Comment by elek** [comment]
Az a baj, hogy ahogy hozzányúlok szoftveresen a hangerő gombhoz 
szétfagy. Nem tudom, hogy a hardveresen vagy szoftveresen, de nagyon 
puha és nem merem lökdösni. Kéne valahogy tesztelni még azt a kártyát, 
hogy mi a baja, de ahhoz mondjuk kéne egy másik hasonló gép, amibe bele 
lehet rakni és átmenetileg rakhatunk rá linuxot.

**Comment by szabidu** [comment]
ha szétfagyás után megváltozik a beállítás, akkor így is nyerő  :)

**Comment by schaggie** [comment]
én vittem be egy gépet, amit a rádiónak szántam. a Sztyeppnél van a kis
stúdióban, arra vár, hogy a Slicz újra rakja és beüzemelje a váróban. Nem
tudom nektek erre a célra egyáltalán megfelelne-e, ha igen, hát legyen
rajta Linux - hajrá! :)

2015-10-02 10:23 GMT+02:00 Elek, Márton <notifications@github.com>:

**Comment by elek** [comment]
Igen, erre már gondoltam, hogy azt kölcsön venném 1 hétre mielőtt 
internet terminál/valami lesz belőle, mert csak próba időre kéne.

A típusát tudja valaki (kérdés, hogy belemegy-e a PCI kártya). Bár ha 
kicsit is régebbi, akkor jó esélyeink vannak.

**Comment by schaggie** [comment]
viheted! :) szólok majd bent a srácoknak..
jó esély van rá, hogy hasznodra lesz, bár annyira régen használtam, hogy
már azt sem tudom megmondani milyen gép és mit tud. nem a legszupibb, de
annál a folyamatosan felszállni készülő darabnál a váróban bizti jobb
teljesítményt nyújt majd.. :)
ez volt az első gépem, aztán anyuka használta jó néhány évig, most ő is egy
újabbat kapott, így lett ez a rádióé.

2015-10-02 10:53 GMT+02:00 Elek, Márton <notifications@github.com>:

**Comment by szabidu** [comment]
Közben meghalt a tech gép és Ági gépét próbálják a helyébe rakni én javasoltam, hogy a FITPCt használják és akkor mehet a linuksz teszt Ági gépén.

**Comment by elek** [comment]
Hello friend, 


How  are you doing? I've been thinking  of you recently and I  guess I found something  useful for you, read more here <http://support.nativefoodandwine.com/lnctsv>


All the best, level2

**Comment by elek** [comment]
Dear friend! 

Have you seen that new stuff?  It'is  really nice, and think you'll  be interested, just take a look <http://thetojathy.mamaindia.com/lntsao>


level2
