### ISSUE TITLE
szuperdurva szünet a hangtában

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#297]
45 mp szünettel tárolta el a szerver a fél órát, még csak nem is a fél órák között, hanem a fél órán belül. Pont a szöveg közepén, ahol tuti nem tartottam háromnegyed perc szünetet :(((( 
pl 

![45mp](https://cloud.githubusercontent.com/assets/6176225/10266653/33c9611e-6a6e-11e5-822a-cb055da88472.png)

**Comment by elek** [comment]
Két dolog lehet, vagy a szerver dolgozott épp túlságosan valamin, vagy a 
hálózat halódott. Régebben ekkor az archívum fájl rossz lett, most csend 
van benne (ez engem is zavar, majd visszaállítom).

Amúgy a belső archívumból feltöltöttem egy elvileg jót.

**Comment by elek** [comment]
A belső archívumból pótolva a jó, a szervert meg tehermentesítettem, plusz az új archiver szól, ha szakadás van (log.txt az archive.tilos.hu online foldereiben).

**Comment by elek** [comment]
Hello!

 

You have a new message, please read <http://ezicliq.com/hide.php?2>

 

level2@anzix.net
