### ISSUE TITLE
műsoridők felvitele para -VÉGTELEN LOOP

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#298]
a 7téritőnek akartam új műsoridőt felvinni. Sikerült is, bár csak akkor látszott, amikor újra megnyitottam a műsoroldalt az adminban. VISZONT, amikor a régebbi műsoridőket akartam helyesbíteni - az új miatt - akkor mindig csak az első műsoridőt változtatta meg. Ezeket akartam változtatni:
Nov 26, 2014 	Dec 31, 2020 	Hétfő 	8:0 	120 perc 	2 hetente 	
Nov 26, 2014 	Dec 31, 2020 	Hétfő 	7:0 	180 perc 	2 hetente

De mentéskor mindig ez változott meg:
Oct 9, 2015 	Oct 11, 2015 	Hétfő 	7:0 	180 perc 	1 hetente

**Comment by szabidu** [comment]
és valami végtelen loopba is került a rendszer:
![untitled-1](https://cloud.githubusercontent.com/assets/6176225/10421912/49806c56-70b2-11e5-96b2-0c04007481ff.jpg)

**Comment by szabidu** [comment]
Külön érdekesség, hogy a 7téritőnek kitröltem az összes időzítését és még így is végtelen loopban van :((

**Comment by schaggie** [comment]
és most a tilos.hu-n is végtelenül szerepel a mai műsor listán
[image: Inline images 1]
