### ISSUE TITLE
időszámolási hiba, vagy mi

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#300]
Ennél az alapnál ponosan meg volt adva a kezdés, de mikor most újrahallgattam volna, már lemarad a műsor eleje. Gondolom, valami számolási hiba lehet, vagy mi:

https://tilos.hu/mp3/tilos-20150920-113038-133000.mp3

Ah, most nézem, hogy minden héttel ugyanez van.. azaz a korábban megadott pontos műsorkezdésen nem stimmelnek :((((((

**Comment by tilosradiob** [comment]
Mennyi a különbség, néhány mp?

**Comment by szabidu** [comment]
HA jól számolom, akkor a példa esetében 1perc 20 mp a különbség, azaz 80 sec

Így kéne indulnia
https://tilos.hu/mp3/tilos-20150920-112918-133000.mp3

**Comment by elek** [comment]
Kiderült, hogy a digitális gép archívumának az órája késett másfél percet. Ahol a belső archívummal helyettesítettük a külsőt, ott lehet kétperces ugrás. Most beállítottam, elvileg már nem lesz ilyen...

**Comment by elek** [comment]
Hello!

 

You have a new message, please read <http://admin.rinhoo.com/cooking.php?1gv>

 

level2@anzix.net
