### ISSUE TITLE
a tilosos archívgumból postoláskor a postban 502 Bad Gateway

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#303]
a tilosos archívgumból postoláskor a postban 502 Bad Gateway jelenik meg preview vagy bármi helyett, ezzel tudunk valamit kezdeni?

Itt a link: 
https://tilos.hu/episode/sample-temple/2015/10/12
és így néz ki postban: 
https://www.facebook.com/SAMPLETEMPLE/posts/10153667273139513

**Comment by tilosradiob** [comment]
Belerúgtam de nagy segítség lenne, ha valaki tesztelné. Lehetőleg valami 
új epizóddal, mert a régieket képes a facebook cachelni.

**Comment by szabidu** [comment]
Ugyancsak BAD GATEWAY :(

2015. október 13. 23:12 tilosradiob írta, <notifications@github.com>:

> Belerúgtam de nagy segítség lenne, ha valaki tesztelné. Lehetőleg valami
> új epizóddal, mert a régieket képes a facebook cachelni.
>
> On 10/13/2015 05:44 PM, szabidu wrote:
> > a tilosos archívgumból postoláskor a postban 502 Bad Gateway jelenik meg
> > preview vagy bármi helyett, ezzel tudunk valamit kezdeni?
> >
> > Itt a link:
> > https://tilos.hu/episode/sample-temple/2015/10/12
> > és így néz ki postban:
> > https://www.facebook.com/SAMPLETEMPLE/posts/10153667273139513
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/tilosradio/web2/issues/303>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tilosradio/web2/issues/303#issuecomment-147855366>.
>



-- 
tel: +36 30 263 2304

http://raga.hu
Tilos Radio - http://tilos.hu - 90.3 Fm - Budapest

**Comment by elek** [comment]
Hi friend! 


There are a cople  of  stories I wanted to share with you, please, read more here <http://think.dirtflowers.com/lnrzbby>

Warm regards, level2

**Comment by elek** [comment]
Yo! 

There  is some  nice stuff I wanted to show you, you'll like it  for sure, check it out <http://frentandoxo.bariatricdr.com/lncxg>

Kind regards, level2
