### ISSUE TITLE
A archivum weboldalon nem jellenek meg a  2013.05.25 elotti musorok

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#304]
A archivum weboldalon nem jellenek meg a 2013.05.25 elotti musorok. Az oldal ures marad.

 Viszont a letoltes renbden mukodik kb 2011-ig.
Szabi tapasztalata szerint:
2013. január 8 és május 24 között nem jelennek meg az archív napok. Elvitte őket a cica.

**Comment by szabidu** [comment]
Úgy látszik nem minden napot érint, de majd mindet a fent jelzett időszakban. pl:
https://tilos.hu/archive/2013/03/08

**Comment by elek** [comment]
Ugyanaz a baj, mint a #307-nél. rosszak a régi adásnapló beosztások. Majd küldöklogot, hogy mi fájt neki...
