### ISSUE TITLE
Az archív naptára csúfirúti

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#306]
Hiányzanak belőle a jobbra-balra nyilak és a napok összecsúsztak
![archiv-naptar](https://cloud.githubusercontent.com/assets/6176225/10729694/7e2b3f82-7beb-11e5-8da4-cda4addf223e.jpg)

**Comment by szabidu** [comment]
Oh, ez nagyon szuper! Már csak a jobbra és balra nyíl hiányzik neki :)

**Comment by reyrodrigez** [comment]
nekem megjelenik szepen
![screenshot 2016-02-28 13 50 46](https://cloud.githubusercontent.com/assets/1655210/13379298/4f3f76b8-de22-11e5-88c8-f0b985cbf821.png)

**Comment by szabidu** [comment]
Már nekem is. Szuper! Köszi!

**Comment by szabidu** [comment]
Sajnos megint megnyitom ezt, mert az aktuális nap NÉHA kilóg a lehetőségből és ezért a dátum vége levágódik. Közben elfelejtett magyarul is.
