### ISSUE TITLE
a régebbi adásnaplók hozzáférése adminból

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#307]
A 3. utas 2013.07.03-nál régebbi adásnaplóihoz nem tudok adminban odalapozni. Nem lapoz, nyet, nyema, nuku, stb.

Ebbe akartam belejavítani:

https://tilos.hu/episode/3-utas/2011/10/26

**Comment by tilosradiob** [comment]
Az a baj, hogy el van rontva a beosztás. Erre hibákat dobált és ezért 
nem jelenítette meg. Most kijavítottam, hogy csak a logba panaszkodjon, 
de látni fogod, hogy a hetek szét vannak csúszva...

**Comment by elek** [comment]
Nézd meg megy-e, mert ha csak a fenti volt a probléma az kijavult.

**Comment by szabidu** [comment]
mögy! Köszi!

**Comment by elek** [comment]
Hello!

 

You have a new message, please read <http://visercorp.com/african-american.php?uyfy>

 

level2@anzix.net

**Comment by elek** [comment]
Hi,

I've found some nice soundtracks and wanted to share them with you, here is the link  <http://wow.gs-reo.com/lntieuz>

Typos courtesy of my iPhone, level2@anzix.net
