### ISSUE TITLE
iPhone Podcasts hiba

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#308]
Megpróbáltam az iPhone Podcasts app-jével előfizetni a Nemzeti Felkelésre a https://tilos.hu/feed/show/nemzeti-felkeles linkkel, de a "The provided link is not a valid Podcast" hibaüzenetet kapom. Rossz app-et használok, vagy máshol a hiba ?

**Comment by elek** [comment]
Működik?

**Comment by szabidu** [comment]
nekem úgy tűnik :)

2015-12-29 10:48 GMT+01:00 Elek, Márton <notifications@github.com>:

> Működik?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tilosradio/web2/issues/308#issuecomment-167757725>.
>



-- 
tel: +36 30 263 2304

http://raga.hu
Tilos Radio - http://tilos.hu - 90.3 Fm - Budapest
