### ISSUE TITLE
ttt upgrade

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#309]
A ttt elfogad oldalra következők kellenének:
- [x] jól látható, piros színű PROGRAM link bootstrap a hely aktuális programjához (HA VAN NEKI!)
- [x] a hely face és weboldal is megjelenne bootstrap módon
- [ ] az oldal tetejébe kéne egy CAROUSEL a támogatók logójával és az egyes logóra kattintva jöhetne az anchor az oldalon lévő leírásra/programra - mindezt úgy, hogy mobilon is jól látható legyen. Talán ez megteszi: http://www.w3schools.com/bootstrap/bootstrap_carousel.asp
- [ ] google analytics eventek bekötése a gombokra

**Comment by reyrodrigez** [comment]
@szabidu hány támogató van? Talán szépen kirakni a logókat egy gridben jobb lenne mert egy karusszelben ha valaki a végefelé van sosem fog látszani. Mobilon meg egy dropdown is megteszi.

**Comment by szabidu** [comment]
36 elfogadóhely van. A lista hosszú, ezért is agyaltunk, hogy egyszerűsödjön (bootstrap linkek), illetve  az oldal tetején lévő carousel egy extra ajánlat lehetene, ami miatt felfigyelhet a látogató egy-egy új, vagy kiemelt elfogadóhelyre.
itt vannak: https://tilos.hu/ttt/elfogad

**Comment by szabidu** [comment]
Ilyesmit találtunk ki az elfogadóhely oldalnak:
![elfogado](https://cloud.githubusercontent.com/assets/6176225/10904314/993f75c2-8212-11e5-859f-4be9e69d7447.jpg)
Az egész ügy azért fontos, mert sokan hisszük, hogy ez a rádió egyik legjobb futó projektje, ami a hosszú távú gazdasági függetlenséget is jelenthetné.

**Comment by szabidu** [comment]
Elkezdtem minimálban megcsinálni, csak az a gond, hogy a hangtár miatt feketék a linkek :(
https://tilos.hu/ttt/elfogad

**Comment by tilosradiob** [comment]
Szerintem ez nem a legjobb irány. Ha már ilyen strukturált az adat be 
kéne írni inkább adatbázisba. Ha belépnél úgy, ahogy gitterben írtam, 
akkor oda fel tudnád vinni az elfogadó helyeket...

**Comment by schaggie** [comment]
Sziasztok!

Itt (valamiért) fontosnak tartom megjegyezni, hogy a kártya online
vásárláskor egyenlőre sehol nem érvényes.

Köszi

2015-11-03 20:39 GMT+01:00 tilosradiob <notifications@github.com>:

**Comment by reyrodrigez** [comment]
mit szolnatok valami hasonlohoz:
![screen shot 2015-11-04 at 16 14 39](https://cloud.githubusercontent.com/assets/1655210/10942196/3fb78410-830f-11e5-931b-4c54add6b684.png)
[Bootstrap custom thumbnail componens](http://getbootstrap.com/components/#thumbnails-custom-content) kisebb altalakitasssal.

**Comment by szabidu** [comment]
Nagyon jól néz ki. 35 elfogadóhely van. Jó be kéne méretezni, illetve Jánosnak szuper ötletei vannak, hogy mivel bővüljön a TTT adatbázis:
Elfogadó helyek térképen. (p2)
Mi van a közelemben? (p2)
Vezess oda (a kiválasztotthoz). (p3)
Vásároljunk együtt – randi játék. (p4)

**Comment by schaggie** [comment]
nagyon szép! :)

**Comment by reyrodrigez** [comment]
Miért feketék a gombok defautban? Ez valami tudatos döntés vagy csak véletlen?

**Comment by szabidu** [comment]
Rónyai Marci barátunk tervezte az oldalt, de sajnos ő már nem tudja megfelelni ezt a kérdést: https://tilos.hu/page/memento-ronyai-marci

**Comment by reyrodrigez** [comment]
Kiment egy update a kepekkel, de az `/api/v1/ttt/business/bravo/photo.jpg` url alatt nem jelennek meg se a test se az eles kornyezetben.  Illetve a test.tilos-ra nem megy ki a deploy.
