### ISSUE TITLE
eltűnő műsorkészítők

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#312]
Lehet, hogy az okozza, hogy kitörli a polgári nevét és ettől kezelhetetlenné válik (hisz a semmire utána nem lehet szerkesztés céljából kattintani). Talán az lenne a legjobb, ha senki nem tudná a saját nevét szerkeszteni, csak az admin

PL:
https://tilos.hu/author/samulkow

**Comment by elek** [comment]
Igen, ezt valszeg kéne javítani, de szerkeszteni így is lehet:

https://admin.tilos.hu/author/samulkow
