### ISSUE TITLE
eltűnt műsorkészítő fotók

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#314]
Egy sem látszik a műsorok oldalán. PL: 
![nevtelen](https://cloud.githubusercontent.com/assets/6176225/11363973/6f85bf5c-929d-11e5-90cd-a8a336992c85.png)

**Comment by elek** [comment]
Ó, ez tudom hol tünt el. Hamar meglesz....

**Comment by szabidu** [comment]
Néztem, hogy beestek-e a sublót mögé, de nem...

**Comment by elek** [comment]
Rossz helyen kerested, a szőnyeg alatt volt...
