### ISSUE TITLE
nem megy a műsorok névváltása (alias)

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#316]
hiába mentem el látszólag az új aliast, nem mentődik el. Pl ennek neve már régóta Gondolatbátorság, de még mindig a fél évvel ezelőtti neve az alias
https://tilos.hu/show/legyen-tilos-a-gyuloletbeszed

**Comment by elek** [comment]
Igen, erről tudok. Adatbázis denormalizálás + az én lustaságom. Így jár aki nevet vált :-P (Na jó, persze, hogy javítgatom...)

**Comment by szabidu** [comment]
jaj

**Comment by elek** [comment]
Megy, de ne használd, mert cache miatt újra kell indítanom az egészet... A gondolatbatorsagot megcsináltam, ezzel épp megöltem az összes eddig meglévő linket, amit eddig bárhova be volt linkelve a régi műsor néven.

Tehát nem egy hasznos funkció...
