### ISSUE TITLE
iOS javítások és hibák

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#321]
- [x] az adásba telefonálás ne egy gombnyomás legyen. "Tényleg betelefonálsz?"
- [ ] más appal simán megy a tilos stream lejátszása, de ezzel mindig megakad és olyankor még ki is lép
- [ ] a LIVE - ARCHIV megjelölés egyértelműbb legyen (régebbi iPhone-on nagyon kicsik és nehezen értelmezhetőek)
- [ ] Nem működik az archív funkció. Nem tölti be a régebbi epizodokat egy adott adásnál.
- [ ] Pontosabban definiálni kéne, hogy mit csinál a fejléc böngészéskor
- [ ] Mi az a kis CD a fejlécben?
- [ ]  Kéne crosslink az alkotókhoz
- [ ] A műsorkészítők között csak az aktívakat kéne megjelentetni
- [ ] Miért van egyik műsorkészítőnél szürke, másiknál fekete default avatar?
- [ ] Timeline nem frissíti az infót (az idő megy, a műsor címe nem változik, marad annak műsornak a neve kiírva, amelyiknél megnyitottam)
- [ ] Időnézetben legyen rendes naptárnézet is, hogy ne kelljen naponta visszatekerni egy évet pl.
- [ ] Böngésző nézet tetejébe keresőmezőt mindenhova!
- [ ] Szövegek balra zárva legyenek
- [ ] A műsorkészítők listájában többszörösen szerepelnek emberek
- [ ] ha olyan funkcióra kattintok ami még nem működik akkor kilep az alkalmazás
- [ ] mai nap műsorlista nem jön fel csak a dátum
- [ ] Bal felső play gomb nem működik, kilép
- [x] iPhone 4s-en eccerűen semmit nem csinál
- [ ] Iphone5 9.1 verzioval egyaltalan nem tudok tilost hallgatni. Archiv anyagokat nem latok. 
  Napi bontast sem. Nap valtasnal kilep az appbol

**Comment by schaggie** [comment]
Timeline nem frissíti az infót (az idő megy, a műsor címe nem változik, marad annak műsornak a neve kiírva, amelyiknél megnyitottam)

Ez nekem PCn, pl. firefoxban is így van. Marad a mûsorcím amíg F5-öt nem nyomok.

**Comment by gezabela** [comment]
BUGOK
- finn idozonat hasznalva az archiv bongeszese jol mukodik, de amint egy adast le akarok jatszani, az API-nak a finn idot kuldi el, igy mindig egy oraval kesobbi adas megy (pl: a csonka itteni ido szerint 11kor kezdodik, helyesen mutatja az listaban, rakattintok, majd elkzedi jatszani a magyar ido szerinti 11 oras adast) (+++)
- gyakran leall a lejatszas, legkellemetlenebb pl. amikor beesek egy meetingre, elotte leall a lejatszas, kirantom a fulhallgatot a telefonbol, majd teljesen random modon neha a jatszas elindul. Amikor kikapom a fulhallgatot az app nem kene ujrainditsa a lejatszast csak ha rakattintok a lejatszasra (+++)
- neha ha leall az elo adas, akkor csak ugy tudom ujrainditani, ha elobb elinditok barmit az archivumbol, majd ismet elinditom az elo adast (++)
- erzes:archiv mindig ora ötkor indul es minden következő óra ötkor megall, ujra kell indítani. Újra csak úgy lehet indítani, hogy előrefele birizgálja az ember az idővonalat (?), ha hátra, akkor megesik, hogy  ismét megáll ugyanott (++)
- a panelek kozti valtoghatasnal gyakran szetesik a layout, a "fekete" screenshot eseten az a ciki, hogy az aktualis kepernyon valo klikkelgetes triggerel egy masik panelen esemenyeket (ebben az esetben talan egy musor oldalat nyitja meg, de erre nem emlekszem teljesen) (+/++)
![img_0110](https://cloud.githubusercontent.com/assets/18413761/14451822/bfe882dc-0092-11e6-9566-ed6e4d647016.PNG)
![img_0277](https://cloud.githubusercontent.com/assets/18413761/14451821/bfe7bd0c-0092-11e6-9bd7-706d2bcf2618.PNG)
- (nekem) nagyon nem nyilvanvalo, hogy hogy es mikor lehet betelefonalni (egyszer majdnem megtettem :D ), de itt nem zarom ki, hogy a felhasznaloban van a hiba (+)



JO LENNE HA
- van-e esely valamilyen kisebb bitrataju streamet hallgatni? Nem lenne rossz egy 32/64 kbps-os HE-AAC stream, ami az MP3-mal ellentetben hallgathato minoseget produkal (nem jot, de fenyevnyivel jobbat). Jo lenne azoknak is, akiknek korlatos adatforgalommal rendelkeznek  (+++)
- programon belul letolteni archiv adasokat es ott meghallgathatni! (++)


(IPhone 6 16Gb, v9.3.1)

**Comment by gezabela** [comment]
BUGOK:

- elo adast leallitom, nehany ora mulva megint az elo adast akarom hallgatni, de az "elo adas" panel meg mindig azt hiszi, hogy heany oraval ezelott vagyunk, ott folytatja a lejatszast, ahol abbahagytam. Csak ugy lehet elo adast hallgatni, hogy elinditok valami archivot es vissza az elore (+++)
- neha a tilos app hatterbe valo betolasa soran bekrepal a hang, elkezd akadozni. Nem tudom egyelore reprodukalni, eleg esetlegesnek tunik (++)

**Comment by szabidu** [comment]
Jelenleg azt taapsztalom az app-al, hogy sokkal jobban működik mint nyár elején, de pl.: ha felhív valaki, miközben az élő műsort hallgatom lehalkul, ami jó és ha véget ér a hívás, a műsor nem folytatódik tovább, ha pedig én indítom el akkor inteligensen ott folytatja ahol abbahagyta, de ennek pedig az a következménye ha elfelejtem, hogy mikor van a műsor vége, egyszerűen csak megáll az adás (azt gondolnánk, hiba van az antennával, internettel, pedig nem), mert véget ért az adás ideje, ezt nagyon jól érzékeli az app, de én nem szereném, hogy ez megáljon.

Ez lehet természetesen annak a következménye is, hogy a Tunein Radio app-t hasznaltam es abban pont ugy voltak, ahogyan en azt hianyolom.

Nem mindig egyértelmű, hogy az élő adást hallgatom-e vagy egy "archivált" felvételt, amit a telefon archivál az appon, ha megállok a hallgatásban ott folytatja, de néha jobb az élő stream, számomra.
Talán itt még leírhatnám, hogy az ÉLŐ kiiírást nehezen sikerült észrevennem, így hetekkel később tünt fel, hogy ott lehet frissíteni a "stream"-t, de nem mindig reagál, lehet érdemesebb lenne nagyobbra venni?

**Comment by szabidu** [comment]
- [ ] a seek sem igazán működik, vagyis eléggé random
- [ ] Vannak napok, amikor pedig scratch-elni kezdi az adást a program - pedig minden más fut rendesen. Ma pl. kristály tisztán hallom a Nemzeti Felkelést itt Tel Avivban, de a te hangod, Szabi tegnap mixbe ment át a 3. utas végén.. És nem az effect miatt, amit a híreknél használtál
- [ ] fejlesztés: a pontos kezdést ismerje fel az app - ezt utólag állítjuk be az egyes műsoroknál

**Comment by szabidu** [comment]
UI dizájn terv: https://www.instagram.com/p/BMRgN1DATlh/

**Comment by intonarumori** [comment]
Szabi,

Az én kérdésem az lenne, hogy mikor kapjuk már meg végre a műsorokhoz tartozó képeket.
A régi design teljes mértékben azokra alapult, és mind szép és jó, hogy első körben kimaradt a szórásból, de én személy szerint nem release-eltem volna addig amíg meg nem jön. Hónapokkal ezelőtt jeleztük, hogy várjuk.

A másik problémám, hogy az API-t meg útközben a backenden megváltoztatták mindenféle verzióváltás nélkül.
Ezért nincs az appban ott jópár információ, pl műsorlistában a készítők nevei.
Ügy tűnik a webesek a web kliensnek megfelelően ezt kedvükre változtatják mindenféle tekintet nélkül a mobil appokra.

Amíg ezek nincsenek tisztázva, addig én biztosan nem fogok semmit csinálni, mert csak árral szemben evezünk, dolgozunk miközben a mi kéréseinkre semmiféle választ nem kapunk.

Dani

**Comment by gergelyjanos** [comment]
Szia Dani!

Api kérdésekben hozzám is fordulhatsz, mert én a windows mobilt fejlesztem és közel vagyok Marcihoz (Web fejlesztő csapat), hogy konkrét problémákkal bombázzam . 

Üdv. János

**Comment by szabidu** [comment]
Szia Dani!

A műsorokhoz az új oldal indulása óta nem tartoznak képek. Jelezted, hogy várod, de sajnos nincsenek képek. Marci biztos segíteni fog api ügyben.

**Comment by intonarumori** [comment]
API problémáim:
- műsorok listázásánál nem tudom megjeleníteni a műsorkészítők neveit mert nincs benne az adatban, régebben benne volt, de eltünt verziózás nélkül
- képekre azt a választ kaptam, hogy lesznek, a facebookról áthúzva, most ennek ellenkezőjét mondjátok, miért?
Ha kell egyesével feltöltögetem őket a facebookról, csak legyen lehetőség egy cover kép csatolásához

Én személy szerint száraznak tartom mind a tilos oldalt, mind az appot a képek nélkül.
Ez lenne az egyetlen módja, hogy valami karartert vigyen bárki a műsora profiljába.
Twitter, facebook, mixcloud, soundcloud. Mind rendelkezik profilképpel és coverrel, miért olyan nehéz ezt nekünk is alkalmazni?
Arról nem is beszélve, hogy ha a Facebookon megosztasz egy tilos linket, mindig ugyanazt a képet kapjuk a feed-ben, miért ne lehetne ez a műsorkészítő saját képe?

Részemről a deal az hogy a képek és az api frissítése után tudok ennek időt szentelni.

PS. Amúgy a design tetszett, és nagyon közel áll az eredeti tervhez.

**Comment by szabidu** [comment]
Velem beszéltél kép ügyben. Az én ötletem volt, hogy a face borítókat behúzzuk, de egy ötletet kimondani és megcsinálni két különböző dolog. Ahogy te is sok munkát fektettél az appba, más sok munkát fektet az oldal programozásába. Sajnos azonban mindenkinek véges a nonprofit ideje. Én köszönöm az eddigi munkádat is.
PS: még az sem biztos, hogy a face borító behúzása a legjobb ötlet...

**Comment by szabidu** [comment]
Kárpáti Laci már új appot fejleszt.
