### ISSUE TITLE
aktuális műsor nevének váltása

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#322]
Jó lenne, ha az aktuális műsornév az épp futó műsor neve lenne, akkor is, ha egész nap hallgatom. ez régen oldalfrissítéssel volt megoldva, de már biztos van rá más, szupi megoldás.

**Comment by elek** [comment]
Kik kéne próbálni hátha megy. Csak nekem mindig bezáródnak az ablakaim...

**Comment by szabidu** [comment]
Nekem úgy tűnik, hogy megy :) ÉLJEN!
