### ISSUE TITLE
nem lehet új mixet menteni :(((((

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#324]
Rányomok a mentésre és semmi nem történik.

**Comment by elek** [comment]
És most?

**Comment by szabidu** [comment]
most se :(

**Comment by szabidu** [comment]
pedig még mindig nem :(

**Comment by elek** [comment]
Megy az, csak véletlen kötelező lett a content mező.

**Comment by szabidu** [comment]
Nem megy, pedig azt is kipróbáltam, hogy egy egész pontot teszek a traklistába.

**Comment by elek** [comment]
Nyomj egy screenshotot, hogy milyen adatokkal próbálod, mert nálam töre megy...

**Comment by szabidu** [comment]
![3 utas](https://cloud.githubusercontent.com/assets/6176225/12432671/e0226d1a-befc-11e5-8176-9b09d8cab8bf.png)

**Comment by szabidu** [comment]
Sajnos még mindig nem megy se rókával, se krómmal :(

**Comment by elek** [comment]
Hátha most....

**Comment by szabidu** [comment]
yipppi!!!
