### ISSUE TITLE
kereső tudatlansága

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#325]
kicsit bizonytalan a kereső, hogy talált-e valamit:

pl:
https://tilos.hu/search/vekerdy

**Comment by elek** [comment]
Akiknek nem adtak hírt róla meglátják, és akik semmit sem hallottak megértik.

**Comment by elek** [comment]
((persze nem tökéletes, de régen csak induláskor indexelt, azért hiányzott a vekerdy is, most meg óránként és kicsit jobb lett))

**Comment by szabidu** [comment]
Szuper!
