### ISSUE TITLE
nem klikkelhetők az adásnaplók - BIGBUG

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#327]
Éppen töltöttem fel adásnaplót, de ezek a tilos.hu sima felhasználó felületéről nem klikkelhetők, tehát a tartalmát nem tudja megtekinteni az egyszerű user.
Safari ban, Firefoxban és Chrome-ban próbáltam.

**Comment by elek** [comment]
Igen, ezt már javítottam, csak elfelejtettem upgradelni az éjszaka.
