### ISSUE TITLE
 https admin para

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#331]
safari Version 9.0.3 (11601.4.4)

az admin felület használata után állandóan https alatt próbálja megnyitni az archivumot, és folyamatosan hibaüzeneteket dobál az oldal, nem tudok semmit visszahallgatni stb.
![screen shot 2016-02-27 at 18 11 56](https://cloud.githubusercontent.com/assets/6176225/13374311/2005469e-dd81-11e5-939c-99a80fd82c7d.png)

**Comment by elek** [comment]
Ez valami mágikus hiba, de elvileg most már nincs ilyen, max 1x, de utána automatikusan törli a rossz auth adatokat.
