### ISSUE TITLE
social share kicsinosítás

### ISSUE THREAD

**Issue by reyrodrigez** [tilosradio/web2#332]
![screenshot 2016-02-28 13 49 49](https://cloud.githubusercontent.com/assets/1655210/13379308/94da48ce-de22-11e5-91b1-76f7b34e4303.png)

og metak hibasan vannak bekotve

```
<meta name="og:image" content="http://tilos.hu/images/kockalogo.png"/>
<meta name="og:site_name" content="Tilos Rádió"/>
<meta name="og:title" content="{{pageTitle}}"/>
<meta name="og:description" content="{{pageDescription}}"/>
```

**Comment by szabidu** [comment]
Hova kéne kötni mit?

**Comment by reyrodrigez** [comment]
a `pageTitle` meg a `pageDescription` hianyzik. Ha azok be kerulnek, csinosabb es informativabb lesz a facebookos megosztas doboz.
