### ISSUE TITLE
hozzáférés csak a saját adásnaplókhoz

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#335]
Jó lenne, ha csak a saját műsoraik adásnaplóját tudnák szerkeszteni a műsorkészítők. Vagy ez feature és nem bug?

**Comment by elek** [comment]
Feature. Az volt a koncepció, hogy megbítunk egymásba és hátha valaki author töltögeti a hiányzó adásnaplókat...

**Comment by elek** [comment]
De ha rossz így, akkor tmeg lehet javítani.

**Comment by szabidu** [comment]
Jobb lenne, ha csak a saját adásnaplóhoz férnének hozzá.
