### ISSUE TITLE
admin szerkesztési hibák, vagy mik

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#336]
Szinte bármit csinálok adminban (megnyitok, javítok, mentek, adásnaplót, mixet stb). HI HE TET LE NÜL lassú és

ilyeneket beszél:
Ismeretlen hiba történt: 502

lassúság: 
egy adásnapló megnyitása: 7 mp
mixoldal: 10 mp
admin oldal megnyitása: 15 mp

**Comment by elek** [comment]
Szerintem elmúlt.(ugye?) a szerver volt lassú....

**Comment by szabidu** [comment]
Nem igazán. Most pl az oldalak lista megnyitása (page lista) 19 mp-ig tartott. Egy perccel korábban azonnal nyílt. Sok gépen próbáltam és van ez a lassúság. 
VISZONT a hibák eltüntek, ami szuper!

**Comment by szabidu** [comment]
Visszajöttek a hibák is :( 
Ismeretlen hiba történt: 502

**Comment by elek** [comment]
Hol, mikor?

**Comment by szabidu** [comment]
A beírás előtt 3 perccel (9:00) Tűzróka, admin felhasználó. Bármire klikkelek a bal oldalon (műsorok, készítők stb.)
