### ISSUE TITLE
TTT böngésző para - BIGBUG

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#340]
a TTT oldal nem nyílik meg egyáltalán :(( - ez utóbbi naaagy baj. 
A tilos oldal sem nyílik meg firefox, chrome és Safari böngészőkben. Azt mondja, hogy mindenfajta fail van :(

![nevtelen](https://cloud.githubusercontent.com/assets/6176225/13665925/329208a6-e6af-11e5-9fa8-406d07f18002.png)

![ttt](https://cloud.githubusercontent.com/assets/6176225/13665926/34c80792-e6af-11e5-94f5-b875c9469ad0.png)

**Comment by elek** [comment]
Nálam jónak tűnik. Biztos még mindig?

**Comment by szabidu** [comment]
már megy, köszi!
