### ISSUE TITLE
pap dávid belépése

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#341]
Amikor be akar lépni a friss jelszavával ezt kapja:
"Request method 'POST' not supported"
HA friss jelszóemlékeztetőt kér, ugyanez a helyzet

**Comment by szabidu** [comment]
Azóta még 3 ember jelezte, hogy nem megy :(

**Comment by szabidu** [comment]
+2 :(

**Comment by elek** [comment]
please test

**Comment by elek** [comment]
meg ne

**Comment by elek** [comment]
Viszont most már igen.
