### ISSUE TITLE
face borító behúzás

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#347]
Az iOS apphoz kéne egy olyan api, ami hetente behúzza és a szerveren tárolja a műsorhoz bejegyzett face oldal aktuális borítóját.

**Comment by rudywaltz** [comment]
i think we are to far for this

**Comment by szabidu** [comment]
There was an offer from an Apple developer to make a new iPhone app if we can somehow connect every show on tilos.hu with its Facebook cover.
