### ISSUE TITLE
vissza a hiba.tilos.hu oldalt

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#349]
Szeretném visszakérni a hibakezelő hiba.tilos.hu oldalt.
Bár a rádió főtechnikusa az offline üzenetfalra szavazott, a hiba.tilos.hu egy mindenki által átlátható rendszer. Még ha a főtechnikus nem is használa, nekünk is jó lehet, meg a tagságnak, aki láthatja, hogy mi vár még megszerelésre.

**Comment by szabidu** [comment]
Ehhez nem használható a bazis.tilos.hu oldalon a létrehozott hiba csatorna???

**Comment by elek** [comment]
Hiba bejelentéshez használható (sőt arra tök jó lenne), todo list kezelésre nem. Szerintem első körben lehetne egy google docs sheet is, hátha azzal konfortosabbak az emberek. Szívesen csinálok átirányítás a hiba.tilos.hu-ról valami spreadsheetre a zöldstúdiós linkhez hasonlóan...

**Comment by szabidu** [comment]
a google sheet nagyon jó ötlet. Kérlek csinálj olyan átirányításosásozást!

**Comment by elek** [comment]
Na de melyik sheetre?

**Comment by szabidu** [comment]
Nem tudom, hogy melyik form lenne a legjobb rá....

**Comment by szabidu** [comment]
Ide kérek szépen egy mutatást a hiba.tilos.hu-ról: https://docs.google.com/spreadsheets/d/1EiBy-ydzYNylxFM1dKAHnpLFO6SEg0Sd1gm1uRTu1W4/edit?usp=sharing
