### ISSUE TITLE
404 oldal hiányzik

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#353]
Eltűnt a 404-es oldal: https://tilos.hu/show/3-utas/asasdf
Csak egy fejléc és lábléc látszik, pedig a megnyitott oldal nem létezik és 404-es oldalt kéne megnyitnia

**Comment by reyrodrigez** [comment]
@szabidu hogy érted hogy "önmagába zárul"? Ha megnyitok egy [nem létező oldalt](https://tilos.hu/show/3-utas/asasdf), ugyan nincs 404-re vonatkozó tartalom, de tudok navigálni és visszalépni a historyban.

**Comment by szabidu** [comment]
Eltűnt a 404 oldal vészjelzés, pedig az praktikus :)

**Comment by szabidu** [comment]
A visszalépős dolog megszűnt, már csak a 404es oldal hiányzik
