### ISSUE TITLE
nem jelenik meg a lead

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#363]
Ezért nem lehet kiemelt tartalmat rakni a nyitóoldal tetejére :((((

**Comment by reyrodrigez** [comment]
@szabidu hol nem jelenik meg, tudsz linket küldeni?

**Comment by szabidu** [comment]
A lead egy kiemelt tartalom lenne a tilos nyitó bal oszlopának tetején (ahol most hardkódolva van Ákos temetése). Nem tudok most csinálni, mert az oldalak nem szerkeszthetőek :(((( https://github.com/tilosradio/web2/issues/409

**Comment by rudywaltz** [comment]
ez még áll? hol lehet kiemelt tartalmat szerkeszteni?

**Comment by szabidu** [comment]
Létre kell hozni egy PAGE-t és a alias mezőbe ezt kell írni: lead

**Comment by rudywaltz** [comment]
Sajnos ha éppen nincs lead akkor az endpoint hibát dob és az megjelenik az oldalon, így csak elő tudtam készíteni, ha szükség van rá miután beállítottad a leadet a web2-frontendben a vissza kell állítanni a kikommentezet sorokat.
https://github.com/tilosradio/web2-frontend/blob/master/client/main/Index.js#L33-L35

<img width="810" alt="screenshot 2018-11-06 09 23 07" src="https://user-images.githubusercontent.com/395555/48052098-549a8180-e1a7-11e8-9a3c-daa75581427a.png">
