### ISSUE TITLE
nem megy a keresés

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#375]
az oldalon nem adja ki a keresés az egyes műsorokat sem :(((
indiai
electrocat
talán semmit nem ad ki :(((

**Comment by reyrodrigez** [comment]
a `https://tilos.hu/api/v1/search/query?q=indiai` endpoint 502 hibat dob. @elek van valami otleted?

**Comment by djtomanek** [comment]
Az 5 programozó közül, aki jelentkezett hibajavításra vendégem lesz az a Tilos Maratonon egy bármilyen italra, aki megjavítja ezt a hibát (vagy persze bárki más is, aki megteszi). 
...szóval igen, semmilyen szóra nem hoz fel találatot az, amikor a főoldalunk jobb felső sarkában rákeresnénk valamire, lásd pl. mondjuk ezt is: https://tilos.hu/search/zene

**Comment by djtomanek** [comment]
(Érik a gyros tál! Óóriási köszi, Marci! ;) )

**Comment by szabidu** [comment]
Megint nem megy a keresés :((((((

**Comment by szabidu** [comment]
Megoldás lehet a nyitóoldali - nem működő - keresés helyett ez? https://duckduckgo.com/search_box

**Comment by reyrodrigez** [comment]
@elek gyros tál overload?

![image](https://user-images.githubusercontent.com/1655210/31505242-5b6939ca-af6c-11e7-8f0f-62483f10bc68.png)
