### ISSUE TITLE
levél műsorkészítőknek hiba

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#381]
BIZONYOS ESETEKBEN, pl a 7 térítő műsornál ezt a hibaüzenetet kapja, aki a tilos oldalon keresztül (levél a műsorkészítőknek) akar kapcsolatot kiépíteni:
Validation failed for argument at index 1 in method: public hu.tilos.radio.backend.data.response.OkResponse hu.tilos.radio.backend.show.ShowController.contact(java.lang.String,hu.tilos.radio.backend.show.MailToShow), with 1 error(s): [Field error in object 'mailToShow' on field 'captcha': rejected value [null]; codes [NotNull.mailToShow.captcha,NotNull.captcha,NotNull.java.lang.String,NotNull]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [mailToShow.captcha,captcha]; arguments []; default message [captcha]]; default message [nem lehet null-érték]] 

Ugyanez a levélküldés a 3. utasnál pl simán megy.

**Comment by djtomanek** [comment]
...és a (példában írt) 7 térítőnek milyen email cím van megadva a rendszerben? Egy működőféle? 
Legalábbis a Bossa Bom Dia-nál működik az üzenetküldés rendben (most kipróbáltam), de gondolom/talán azért, mert ott a bossabomdia kukac gmail, egy működő fiók van beállítva.

**Comment by szabidu** [comment]
megy a 7téritőé is, mindegyik műsorkészítő címe benne van.
A gond az, hogy NEM MINDIG megy... valami huncutság miatt

**Comment by djtomanek** [comment]
(...btw az még egy érdekes dolog szerintem, hogy HOL van megadva, ill. HOL LEHET MEGADNI egy-egy műsor mail-es elérhetőségét, azaz azt, ahová küldenie kellene a rendszernek azt, amit valaki a "Levél a műsorkészítőnek" menüpontra kattintva és az ottani cuccokat kitöltve küldene. Mert én pl. most végignyálaztam szerintem az összes pontot az https://admin.tilos.hu oldalon a saját "Műsorkészítő profil" (Móricz Tamás) és "Saját műsorok" (Bossa Bom Dia) alatt és sehol nem láttam azt, hol lehetne megadni a (szerencsére valahogy így is beállított) gmail címemet. Szóval azért az sem tűnik egy 100-as megoldásnak számomra... :( )

**Comment by szabidu** [comment]
Csak a központi admin tud megadni mailcímet egyes műsorkészítőknek. A LEVÉL MŰSORKÉSZÍTŐKNEK linkre kattintva az adott műsor össze műsorkészítőjének megy levél arra a címre, amit az admin az egyes műsorkészítőknek megadott.

**Comment by djtomanek** [comment]
Most küldtem hibaüzenet nélkül egy üzenetet a 7 térítőnek ("Message was succesfully sent" vagy valami hasonló egysorost kaptam), ÚGY, HOGY BEIKSZELTEM azt a "Nem vagyok robot" captcha-t is, ami a hibajegy létrehozásakor beillesztett hibaüzenetben ezerszer szerepel (mármint a captcha) szó. 
...szóval annyi lenne ennek a "hibának" a megoldása, hogy úgy kell küldeni üzenetet, ahogy kéri a rendszer? ;)

**Comment by djtomanek** [comment]
....bár a "mailToShow" is többször szerepel a kezdő hibaüzenetben. Mindazonáltal én azt is kitöltöttem rendben, ahogy a captcha-t is beikszeltem, és úgy pillanatnyilag átmehetett hiba nélkül az üzenetem.

**Comment by szabidu** [comment]
gy kezdődik a hibajegy: BIZONYOS ESETEKBEN -viszont lezárom ezt az issuet, hátha tényleg csak kósza hiba volt :)

**Comment by djtomanek** [comment]
...igen, szóval szerintem az a megoldás, hogy nem kattintotta be a captcha-t az, aki küldeni akart - LÁSD MOST a csatolmányt, mert kipróbáltam captcha nélkül és pont ugyanazt a szöveget kaptam! 
![uzenet_musorkeszitoknek_captcha_nelkul](https://cloud.githubusercontent.com/assets/26205211/23590528/1bf344f8-01e2-11e7-8330-c61dc9c6d139.png)
