### ISSUE TITLE
Disqus beépítése az adásnaplók alá

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#384]
Valószínűleg rossz helyre tettem be a disqus beépülő modult, ezért nem jelenik meg az egyes adásnapló oldalakon:
https://github.com/tilosradio/web2-frontend/blob/master/client/episode/episode.html
39-59. sor
De hol lehet  jó helye-e?
vagy más okból nem jelenik-e meg?

**Comment by reyrodrigez** [comment]
https://github.com/tilosradio/web2-frontend/pull/7
