### ISSUE TITLE
page title hiba

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#388]
<title ng:bind-template="Tilos Rádió{{pageTitle}}">

nem írja ki a page title-t :(((((((((((

**Comment by gygabor** [comment]
Néztem én is, mert valaki linkelte a tilost facebookra és a cím helyett ezt írta ki: {{pageTitle}}.
Minek kéne egyébként lennie a pageTitle-nek? Most egy üres string ahogy nézem. Ha dinamikusan változik, mire kéne változnia?

**Comment by szabidu** [comment]
Mutatok egy példát. Ez az oldal:
https://tilos.hu/page/alapitvany

page title: Tilos Kulturális Alapítvány - vastag nagyobb betűvel az oldal tetején.

**Comment by gygabor** [comment]
oké. Lassan megértem, hogy működik és azt hiszem megvan a megoldás. A kérdés csak az, hogy ahol nincs egy konkrét cím [(https://tilos.hu/index)](https://tilos.hu/index) oda mit írjak? A jelen esetben pl. magyarul, hogy "Főoldal"? Vagy angolul? Gondolom máshol meg a http requestben van a megoldás, ami a pageTitle lesz. Csak ugye itt több request is van. Bocs, hogy ennyit kérdezek, még biztos fogok, de még kezdő vagyok :)

**Comment by szabidu** [comment]
ilyen oldalak: 
404
index
https://tilos.hu/shows
https://tilos.hu/archive
https://tilos.hu/mixes/dj
https://tilos.hu/mixes/show
https://tilos.hu/mixes/guestdj
https://tilos.hu/mixes/tale
https://tilos.hu/ttt/elfogad
https://tilos.hu/ttt/info

az  egyes epizódoknak sincs page title-ja, pl:
https://tilos.hu/episode/3-utas/2017/04/19

**Comment by gygabor** [comment]
Igen, ezek megvannak. Kb. csak a authoroknál jelenik meg a pageTitle. A pageDescription se látszik. 
A kérdésem, hogy ezeknél legyen a pageTitle ugyanaz mint mondjuk ami a menüben van? 
Pl. : https://tilos.hu/shows -> "Műsorok"

**Comment by szabidu** [comment]
Az lenne a jó, ha ezeknél az adott műsor címe jelenne meg, pl:
https://tilos.hu/show/3-utas

esetében:
**3. utas**

**Comment by szabidu** [comment]
Hopp! A műsorcímek és a műsorkészítő nevek már megjelentek.
