### ISSUE TITLE
kéne egy felugró ablak a tilos.hu-ra

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#390]
Ezzel az infóval:

Kérjük, támogasd adód 1%-ával a Tilos Rádiót, vagy valamely más rászoruló civil szervezetet!
Innen kinyomtatható a kitöltött rendelkező nyilatkozat: https://tilos.hu/.../Tilos-Radio-Egyszazalek-nyilatkozat...
Hogyan rendelkezhetsz adód 1+1 %-áról?
- Az adó 1+1% felajánlásáról az új online felületen, vagy a 16SZJA EGYSZA lapján, illetve az erre a célra kialakított 16EGYSZA jelű nyomtatványon is rendelkezhetsz.
- Az adó 1+1% felajánlásáról a rendelkező nyilatkozatot 2017. május 22-ig kell elektronikusan vagy postán megküldened a NAV-hoz, akár a bevallás részeként, akár külön.
- Ha a munkáltatódat bízod meg bevallási kötelezettség teljesítésével, a rendelkező nyilatkozatot lezárt borítékban 2017. május 10-ig a munkáltatónak is átadhatod.
#TilosRádió1százalék #18002454-2-42

**Comment by szabidu** [comment]
ezt a felugró ablakot mindig az aktuális kampányban használnánk.

**Comment by rudywaltz** [comment]
@szabidu csak ha megígéred hogy nem lesz folyton bekapcsolva (: én a falnak tudok menni tőlük...

**Comment by szabidu** [comment]
megigérem :)

**Comment by rudywaltz** [comment]
Hali,
nem tudom mennyire lesz érthető, de csináltam neki egy dokumentáció félét (ha majd kikerül):
https://tilos.hu/testpage
szívesen segítek majd az első éles használtkor.

**Comment by szabidu** [comment]
Annyira király vagy!
