### ISSUE TITLE
facebook megosztás

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#392]
{{pageTitle}}
{{pageDescription}}

- ezt írja most facebook megosztáskor. Azt mondják itt van megoldás:
http://onlinemarketing.blog.hu/2017/01/24/jol_latszik_a_weboldalad_a_facebook-on

**Comment by gygabor** [comment]
Ezt lattam, de ez ugyanaz a problema mint a {{pageTitle}} volt egy m'sik issueban. A musoroknal es a musorok szerzoinel a megfelelo adatot irja ki. Kicsit tulvallaltam magam a hetre es ezert eltuntem. Meg az volt a tervem, hogy okoskodas helyett csinalok is valamit, amit elfogadtok vagy sem. ugy gondoltam, az produktivabb. Ezen vagyok meg mindig :)

**Comment by szabidu** [comment]
Egy lendülettel 2 issue-t lehet megoldani 🗡
