### ISSUE TITLE
zöld letöltés link felejtős?

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#394]
Már sem firefox, sem Chrome, sem IE böngészőben nem megy a műsorok ZÖLD színű letöltős linkje:
https://tilos.hu/show/francia-hangja

Mindig a böngészőben akarja nyitni.

**Comment by phobophobia** [comment]
Nálam Linux-on (Ubuntu) a 59.0.3071.115 (64 bites) verziójú Chrome-ban és 54.0 (64 bites) verziójú Firefox-ban jelenleg gond nélkül elindul az mp3 fájl letöltése.
Nem csak arról van szó, hogy nálad társítva lett a böngészőben az mp3 fájltípus a böngészőhöz?
Elvileg ez konfigurálható -- például Firefoxban a about:preferences#applications menüben.

**Comment by szabidu** [comment]
Közösségi felháborodás okozta ezt az issue-t, de úgy látszik megoldotta valaki titokban. Talán az idő :)

**Comment by phobophobia** [comment]
Szuper. :) Akkor erre rárakhatjuk a _paranormal_ tag-et.
