### ISSUE TITLE
tilos.hu/egyszazalek

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#396]
Az egyszerűsítés végett lehet egy olyan beállítást kérni, hogy a  tilos.hu/egyszazalek oldal ide mutasson:
https://tilos.hu/page/egyszazalek

csak egy szó a különbség, de egyszerűbb megjegyezni :)

**Comment by rudywaltz** [comment]
now https://tilos.hu/egyszazalek redirect the original page
