### ISSUE TITLE
Ki kéne nyitni a műsorok tagelését a hallgatók felé egyszerű fb connecttel.

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#397]
Ki kéne nyitni a műsorok tagelését a hallgatók felé egyszerű fb connecttel. - ez a javaslat érkezett, ami kicsit egybevág a korábbi fejlesztési iránnyal, mi szerint az aktív, megbízható hallgatók segítenének az adásnapló megírásában stb.

**Comment by quitzngr** [comment]
És hogy ne legyen annyira nagy a tagek szórása, egy a műsorkészítők által megadott alapkészlet, és a korábbi leggyakoribb tagek kiajánlásával indulna a folyamat (mint a delicio.us-nél pl.). De szabadon is be lehet írni új tageket.

**Comment by quitzngr** [comment]
Megfontolandó feketelista bevezetése is, bár nálunk az elég nehezen működne, de jó korpusz lehet hozzá béláink megszólalása a chaten.

**Comment by rudywaltz** [comment]
ezt toljuk el az új honlapig.
