### ISSUE TITLE
jazz stream

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#398]
Megpróbáltam betenni a Jazz Stream linket ide:
https://github.com/tilosradio/web2-frontend/edit/master/client/main/Listen.js

De azonnal pirossal jelent meg és amikor upgrade-eltem, akkor nem is jelent meg az oldal, szóval valahol kihagyok valamit. Melyik fájlba nyúljak még bele?

**Comment by phobophobia** [comment]
Javítva. :)
c0e6355b29ed1cc331512f07c89e66a5d0446804
