### ISSUE TITLE
műsorok pontos kezdési ideje böngészőben

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#401]
Korábban a böngészőben megnyitott lejátszott műsorok idejét egyénileg a böngészőben meg lehetett adni, ami segítség volt, hogy pont annyit töltsek le, amennyit szerettem volna, illetve a pontos adásidőt is ezen keresztül intéztem. Most 040-et dob, ha megváltoztatom a kezdést. Mutatok egy példát:
LEJÁTSSZA: https://archive.tilos.hu/cache/tilos-20170427-180000-200000.mp3
NEM JÁTSSZA: https://archive.tilos.hu/cache/tilos-20170427-180100-200000.mp3 - azt válaszolja:
404 Not Found
nginx/1.4.6 (Ubuntu)

Ez BUG vagy FEATURE?

**Comment by tilosradiob** [comment]
feature. regen  sem ezzel az urlel ment. cache nem kell bele

On May 5, 2017 6:20:49 PM GMT+02:00, szabidu <notifications@github.com> wrote:
>Korábban a böngészőben megnyitott lejátszott műsorok idejét egyénileg a
>böngészőben meg lehetett adni, ami segítség volt, hogy pont annyit
>töltsek le, amennyit szerettem volna, illetve a pontos adásidőt is ezen
>keresztül intéztem. Most 040-et dob, ha megváltoztatom a kezdést.
>Mutatok egy példát:
>LEJÁTSSZA:
>https://archive.tilos.hu/cache/tilos-20170427-180000-200000.mp3
>NEM JÁTSSZA:
>https://archive.tilos.hu/cache/tilos-20170427-180100-200000.mp3 - azt
>válaszolja:
>404 Not Found
>nginx/1.4.6 (Ubuntu)
>
>Ez BUG vagy FEATURE?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/tilosradio/web2/issues/401

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by szabidu** [comment]
úgysemegy :(((
https://archive.tilos.hu/tilos-20170505-113559-123700.mp3

**Comment by tilosradiob** [comment]
tilos.hu archive oldal, nezd meg az urlek alakjat, azr ird at.

ebben meg hianyzik az mp3

de ense tudomfejbol

On May 5, 2017 7:12:07 PM GMT+02:00, szabidu <notifications@github.com> wrote:
>úgysemegy :(((
>https://archive.tilos.hu/tilos-20170505-113559-123700.mp3
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/tilosradio/web2/issues/401#issuecomment-299522170

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by szabidu** [comment]
Értem a cache helyére mp3-at kell írni :))) szuper
