### ISSUE TITLE
adásnapló hibajel

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#406]
Carlos kollégánál jelentkezett.
https://admin.tilos.hu/edit/episode/5830bd51689a2a230fd2222e

![screen shot 2017-05-10 at 13 59 27](https://cloud.githubusercontent.com/assets/6176225/25897852/e0a5cb74-3589-11e7-8b48-19debcc25485.png)

**Comment by szabidu** [comment]
Ma eggyel több hibaüzenetet kaptam. ez fejlődés? :D
![naplo](https://user-images.githubusercontent.com/6176225/28238741-b3f46c16-695a-11e7-980c-50b0349a9db1.jpg)

**Comment by rudywaltz** [comment]
itt a gyüjtő ticket #425
