### ISSUE TITLE
Jazz is dead nappal vs ejszaka

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#408]
a 2 db benne lévő mappakat be lehet allitani, hogy csak nappal, a masikat pedig ejszaka jatsza?
"konnyu" 8h-20h
"free" 20h-8h

**Comment by phobophobia** [comment]
ez zárható, igaz?

**Comment by szabidu** [comment]
Nem. egyfelől nem ez a neve a streamnek, másfelől az éjszaka/nappal nincs megoldva :D

**Comment by phobophobia** [comment]
upsz... értem.
felületesen olvastam. :) azt hittem ez is a fontend-ről szól. (viszont akkor ennek az issue-nak inkább a web2-backend repo alatt a helye.)
