### ISSUE TITLE
szöveges stream

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#410]
Elkészült a szöveges stream induláshoz szüksége hanggyűjteménye. jó lenne beindítani, hogy mihamarabb okosodjanak a hallgatók.

Meg akkor ez is mehetne a nyitóra a "jazz is dead?" stream-mel együtt

**Comment by phobophobia** [comment]
Mi az URL a szöveges stream-hez? (És miért zártad ezt az issue-t?)
