### ISSUE TITLE
november 9-e előtti Zártkörű lányok

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#411]
november 9-e előtti adásnaplók szerkesztésekor csak hibaüzenet jön:
![unnamed](https://cloud.githubusercontent.com/assets/6176225/26482569/6ed605fc-41e8-11e7-8ec5-3b7dae19b973.png)

**Comment by szabidu** [comment]
még mindig fennáll

**Comment by rudywaltz** [comment]
@szabidu Tudnál mutatni egyet ahol biztosan nem megy még most sem?

**Comment by szabidu** [comment]
Úgy tűnik, hogy már megy :)
