### ISSUE TITLE
Ios archive nem megy 22 percnél tovább

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#413]
Valaki hallgat Tilos archívumot rajtam kívül Tilos app-al iPhone-on?
Ma kb öt elmúlt adás visszhallgatásával próbálkoztam, de egyikkel sem ment 22 percnél tovább.
Először azt gondoltam a mobilnetet nem szereti, de aztán WiFi-n keresztül is próbálkoztam és ott is ugyanez a helyzet.
...
 nalam is ajpeden

**Comment by schaggie** [comment]
Öööö.. nekem is ezt csinálja az apple app. Mondjuk még csak három műsort próbáltam meghallgatni, de 22 percnél eddig mind leállt..
