### ISSUE TITLE
podcast hiba+mp4 verzió nem jön

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#421]
RSS olvasóval töltögettem le a szöveges adások mp4 podcast verzióit és hallgattam a buta telefonomon, de úgytűnik az mp4 verzió nem jön le. Én gyorsan átáltam az mp3-ra ami rendben műxik. Gondoltam szólok.

**Comment by szabidu** [comment]
Tudtok róla, hogy a műsorok kb. 3 hete podcast formájában nem letölthetőek?

Biztos, hogy a hiba nem nálam van, más oldalak podcastjai gyönyörűen frissülnek és lejönnek. Másik gépről is próbáltuk, ott sem működik.

„Sima” letöltés működik, de jobb lenne a korábbiakhoz hasonlóan a podcast.

Köszi, hogy megnézitek!

**Comment by rudywaltz** [comment]
elengednénk ezt az mp4 verziót egyelőre, úgy tűnik a tárhelyünk amúgy is eléggé tele van.
