### ISSUE TITLE
winamp

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#423]
Nem működik a népszerű winamp lejátszóval az oldal piros, azaz böngészőn kívüli lejátszójára szóló m3u fájl.
Elek Marcinak nincs winamp a gépén, szóval olyan tudja csak megbindzselni, akinek van :)

**Comment by djtomanek** [comment]
Kiegészítések hozzá: 
A _piros_ gombos, _m3u-s_ linkeket nem lehet behúzni és meg sem lehet nyitni (Add URL-lel) a Winampban, ha úgy teszek, akkor nem jelenik meg ott a sor/track, amit oda akarok-akartam rakni és hallgatni akartam-akarok. Pl.: https://tilos.hu/mp3/tilos-20170918-151612-164925.m3u 
...de amúgy a Tilos-archívumos .m3u-kra ez már elég régóta igaz. 

A _sárga_ gombos, _.mp3-as_ linkeket viszont néhány héttel ezelőttig vidáman, gond nélkül lehetett mind behúzni, mind Add URL-es hozzáadás után hallgatni Winampban.  Néhány hete viszont amikor behúzom vagy hozzáadom, akkor indítás után csak egy "[Error syncing to stream]" hibaüzenetet kapok. 
Pl.: https://tilos.hu/mp3/tilos-20170918-151612-164925.mp3 
Egyelőre még csak az itthoni Winampomon próbáltam a dolgot, de egyrészt láttam már a cseten mástól is hasonló visszajelzést a problémáról, másrészt igyekszem hamarosan valahogy a Tilosos, kékstúdiós Winamppal is megnézni a helyzetet.

**Comment by djtomanek** [comment]
...és még további kiegészítések: 
_**Nem az időintervallumos link/hanganyagképzés** lehet a hiba oka_, mert azokra a félórás hanganyagokra is igaz, hogy jelenleg nem játszhatók le a Winampban, ahol az még nem történt meg (ill. amelyekből az előbbiek képződnek). Pl.: https://archive.tilos.hu/online/2017/09/25/tilosradio-20170925-1500.mp3 
...viszont a többi/_korábbi Tilos-hangtáras hanganyagok **rendben lejátszhatók**_ ott. Pl.: http://bossabomdia.tilos.hu/tomanek-berlin8_summer_sleep.mp3

**Comment by GreenDogh** [comment]
Kipróbáltam és nem müxik, windows 10, de ez egy régebbi vlc (a
legfrissebbel se nyitja meg, azt korábban próbáltam)

.


​

2017. szeptember 27. 9:40 phobophobia írta, <notifications@github.com>:

**Comment by djtomanek** [comment]
Sajnálom, hogy nem sikerül ezt a problémát megoldani (azaz hogy Windows-os számítógépeken nem lehet VLC/Winamp/stb lejátszókba behúzva/dragndropolva, letöltés helyett csak "sztrímelve" lejátszani az archive.tilos.hu oldalon levő hanganyagokat (gyakorlatilag bármelyik adásnapló hanganyagát a sárga vagy zöld gomb alól), mert ezzel szerintem NAGYON sokan szopnak-szophatnak. 
...mert így valami totál szar és nem arra való beépített böngészős, mini lejátszóban próbálkozhatnak csak 1-2 perceket (vagy hosszú adások esetén még nagyobb intervallumokat) tekerni képesen a műsorok visszahallgatásával, úgy, hogy az adások második felének elindulását egy odatekerés után talán türelmük-idejük sincs kivárni a dolgot, 
míg a korábbi 10+ évben csak egyszerűen be kellett húzniuk a Winampba akármelyik archív hanganyagunkat, és még ha az 2-3+ órás is volt, akkor is egy másodperc alatt oda tudtak tekerni akárhányadik óra akárhányadik percének akármelyik másodpercéhez - egyből, pontosan, nem csak mondjuk 4-5 perces intervallumokat előre-hátra.. -, és az 1-2 másodpercen belül vagy akár azonnal el is indult... :(((

**Comment by djtomanek** [comment]
Arra a részére amúgy van tipp, hogy "csak" az archive.tilos.hu helyen levő cuccal van gond? 
Legalábbis ezt behúzva "Error syncing to stream" hibaüzenet jön: https://tilos.hu/mp3/tilos-20171218-160248-170602.mp3  , 
míg _pontosan ugyanazt_, a fenti hanganyagot letöltve, majd a bossabomdia.tilos.hu oldalra feltöltve ez _már behúzható és hibaüzenet nélkül játszható_ Winampban, a Win10-es gépemen: http://bossabomdia.tilos.hu/tomanek-monty_alexander_1.mp3

**Comment by szabidu** [comment]
lezárom, mert a fejlesztési irány úgyis a sajt lejátszó. Túl sok mindennek kell megfelelni, ha a behúzással is törődünk :)
