### ISSUE TITLE
hírek átvétel

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#433]
Más rádiók is szeretnék átvenni a híreinket. Kén egy nyilvános mappa, ahol elérhetőek lennének az egyes feltöltött hírek.

**Comment by tilosradiob** [comment]
http://hir.tilos.hu/kesz/2018/01/25/

On January 25, 2018 1:49:17 PM GMT+01:00, szabidu <notifications@github.com> wrote:
>Más rádiók is szeretnék átvenni a híreinket. Kén egy nyilvános mappa,
>ahol elérhetőek lennének az egyes feltöltött hírek.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/tilosradio/web2/issues/433

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by szabidu** [comment]
sajnos ezek nem működő formátumú fájlok. letöltve 0 hosszúak. Próbáltam más napokon, akkr is ezt mondja.

**Comment by elek** [comment]
Nekem működnek. Ezeket jásza le a stúdió is. Próbáld meg vlcvel
