### ISSUE TITLE
Nem látszanak a mixek!

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#436]
MEG tudjatok mondani nekem kerlek, hogy a mixeket csak nekem nem tolti be vagy jelenleg nem elerhetoek ezek? 
https://tilos.hu/mixes/show

Illetve, hogy hol, mikor talalom meg oket?

Koszi a valaszt!

Udv,
Dani

**Comment by gergelyjanos** [comment]
A mixek apija kb egy hete nem mukodik. ☹
