### ISSUE TITLE
hibaüzi és nem ment adásnaplószerkesztésénél

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#441]
ennél az adásnaplónál:
 https://tilos.hu/episode/szepkilato/2015/07/25

ezt az üzenetet adja:
Hiba: { "serverUsed" : "127.0.0.1:27017" , "ok" : 1 , "n" : 0 , "updatedExisting" : false , "err" : "E11000 duplicate key error index: tilos.episode.$plannedFrom dup key: { : new Date(1437813000000), : false }" , "code" : 11000}

**Comment by rudywaltz** [comment]
esélyes hogy összefügg: #425 ott folytatjuk
