### ISSUE TITLE
bekerülés az ICECAST listába

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#442]
Az Icecast programban is lehet listáztatni a Tilost, hogy a többi 16e rádió között megjelenjen:
http://icecast.org/docs/icecast-2.4.1/yp.html

Itt a lista: 
http://dir.xiph.org/index.php

**Comment by sosandris** [comment]
A config fájlt kell módosítani. Állítólag az /etc/icecast.xml néven fut. Ehhez nincs hozzáférésem.
Itt a módja:
http://icecast.org/docs/icecast-2.4.1/yp.html

**Comment by sosandris** [comment]
Ezt megcsináltam!

@szabidu 
Az Icecastot gondolom újra kell indítani, hogy az módosított konfigot beolvassa.
Így kell még az icecastot újraindítani?
> "if important stream missing: sudo /etc/init.d/liquidsoap restart
> sudo /etc/init.d/icecast2 restart - ha ez sem segít, akkor server restart"

**Comment by sosandris** [comment]
https://dir.xiph.org/search?q=tilos
