### ISSUE TITLE
új műsorkészítő regisztrálásánál akkora hibaüzi, mint ide nagykáta

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#443]
{ "serverUsed" : "127.0.0.1:27017" , "ok" : 1 , "n" : 0 , "updatedExisting" : false , "err" : "The _id field cannot be changed from {_id: ObjectId('5794e9c8605417725a38eea6')} to {_id: ObjectId('57bb01da605417725a38eea9')}." , "code" : 16837}

Ezt a szép üzit jelszóemlékeztető kérésekor dobta.
ez mi ez?

A műsorkészítőt próbából regeltem, hogy lássam az új jelszóemlékeztetőt: laura, laura@tilos.hu

**Comment by sosandris** [comment]
Ezt a MongoDB adja, és valami olyanra gyanakszom, hogy már létezett a Laura az adatbázisban, csak nem az összes adatával, ezért nem tudja a program még egyszer létrehozni (még egyszer). Az egyik program részlet email alapján keresi a usert, a másik username alapján... ezért akadhat össze. Az adatbázishoz nincs hozzáférésem, leellenőrizni nem tudom. Esetleg el tudod küldeni a Laurának a rekordját, és az enyémet, hogy összehasonlíthassam?

**Comment by szabidu** [comment]
TE:
{
    "_id" : ObjectId("5a7c80c06a60904998a7ed0b"),
    "name" : "Sós András",
    "alias" : "sos-andris",
    "email" : "sosandris@gmail.com",
    "introduction" : ""
}

LAURA:
{
    "_id" : ObjectId("5a8d82dd6a60904998a7ed0c"),
    "name" : "Posta Laura",
    "alias" : "lau",
    "email" : "laura@tilos.hu",
    "introduction" : ""
}

**Comment by sosandris** [comment]
Akkor lehet, hogy van még egy _lau_ vagy _laura@tilos.hu_?
Kinek az _id -ja a _5794e9c8605417725a38eea6_ ?
És a _57bb01da605417725a38eea9_ ?

**Comment by szabidu** [comment]
Feladtam! Létrehoztam egy másik felhasználót, hogy azzal teszteljem az új levelet és a belépési helyet. Úgy tűnik, hogy ez a hiba egy egyszeri jelenség volt, ami egy tesztfelhasználót érintett csak. ennél nagyobb bajaink is vannak :)
