### ISSUE TITLE
ACRCloud

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#449]
https://www.acrcloud.com/

Havi 5300 Ft-ért elérhető ez a tartalom-felismerő szolgáltatás, ami hatalmas segítség lenne a Tilosnak és a hallgatóknak. Pitch Shift felismerő rendszerük miatt akkor is felismeri a számokat, ha a lemezjátszó gyorsabban vagy lassabban szól. Van hozzá API. Az alábbi példában a Tilosra van konfigurálva. 

![acrcloud](https://user-images.githubusercontent.com/6176225/37951031-31fe3994-319b-11e8-8d98-9cc0b14404c6.png)

**Comment by szabidu** [comment]
Ádám mondta, hogy be tudná konfigurálni, hogy a streamben ki legyenek írva a felismert dalcímek.

**Comment by ant0nwax** [comment]
http://savonet.sourceforge.net/doc-svn/on2_part2.html

read from "Custom metadata"

**Comment by ant0nwax** [comment]
@szabidu please assign to me

**Comment by ant0nwax** [comment]
This sentence (including HREF links) should be placed on the footer of the startup webpage
[Radio airplay monitoring](https://www.acrcloud.com/broadcast-monitoring) is powered by [ACRCloud](http://www.acrcloud.com/)

we will get

**Comment by szabidu** [comment]
It is already in the foot. ;)

**Comment by ant0nwax** [comment]
@szabidu please update here what you achieved

**Comment by szabidu** [comment]
Tilos Credit card is set to the arcloud account. ready to rock!

**Comment by ant0nwax** [comment]
I just got the advice that this is the way to go:
Just I am not a web-programmer and i hardly understand json

@szabidu  please assign someone who can do this:

Hi There,

Thanks for your email.

You can use the Callback URL to get all of the monitoring results. Unfortunately, we don't have any docs for implement the results on your website or Tunein.

Please let me know if you have questions.
Thanks


Tony Li 

ACRCloud 

Schedule a call with me

Skype: astonysh1590
M: +86-18611325714
T: +86-10-84917612
Website | Blog | Press

**Comment by sosandris** [comment]
I'll try to make it on Saturday. What's your phone nr?
Mine is +36204069640

ant0nwax <notifications@github.com> ezt írta (időpont: 2018. jún. 30., Szo
12:27):

**Comment by sosandris** [comment]
I am planning to go to Tilos tomorrow. I'll have my 2 girls with me, so
I'll have limited resources

ant0nwax <notifications@github.com> ezt írta (időpont: 2018. júl. 3., K,
6:22):

**Comment by sosandris** [comment]
We have 2 choices to display the music currently streamed:
1. every time a visitor arrives to the page and in a certain interval (eg every minute) we poll the service, and display the results. The problem with this approach is that we can poll only 20k times a month, after that every 1k poll costs $2.5-3
2. we use the callback feature, which means that any time it recognizes a new song, it makes a request to a backend. We have to write a program on the backend to capture the request and save the data from the request to a database. Then serve the "what-is being-played" feed from this db.

Even though it is a lot more work, I would go for option #2. We have to agree what should be the backend, my vote would be for Google or Azure cloud. This would be a nice experiment to see if it is worth move some of our stuff to the cloud.
Any opinion?

**Comment by schaggie** [comment]
Hi. 
I may be running ahead of things with this question.. would option 2 be able to extract into a csv to help reporting to NMHH? we currently do this manually and it sucks. Would defo go for option 2 if it could take some load of the job off us! ..if my vote counts at all. :) x
aggie

**Comment by sosandris** [comment]
Yes, we can do reports from the database. To csv or any other form.
You can even do that without option 2. You can log on to the web site of
the service and download any month's data. I will send you a dump in a
minute.

schaggie <notifications@github.com> ezt írta (időpont: 2018. júl. 13., P
21:15):

> Hi.
> I may be running ahead of things with this question.. would option 2 be
> able to extract into a csv to help reporting to NMHH? we currently do this
> manually and it sucks. Would defo go for option 2 if it could take some
> load of the job off us! ..if my vote counts at all. :) x
> aggie
>
> Sent from my SmartiPhants
>

**Comment by szabidu** [comment]
If it works it can be a report to NMHH and even an automatic adásnapló as well .)

**Comment by sosandris** [comment]
Hello @schaggie what format do you need for NMHH? This is what you can download manually from the ACR portal:
[s-M1xLrD2_monitoring_log_201809.xlsx](https://github.com/tilosradio/web2/files/2486864/s-M1xLrD2_monitoring_log_201809.xlsx)

But I can do any format, if you can wait :)

> Hi. I may be running ahead of things with this question.. would option 2 be able to extract into a csv to help reporting to NMHH? we currently do this manually and it sucks. Would defo go for option 2 if it could take some load of the job off us! ..if my vote counts at all. :) x aggie
> […](#)
> Sent from my SmartiPhants
> On 13 Jul 2018, at 17:05, Andris ***@***.***> wrote: We have 2 choices to display the music currently streamed: every time a visitor arrives to the page and in a certain interval (eg every minute) we poll the service, and display the results. The problem with this approach is that we can poll only 20k times a month, after that every 1k poll costs $2.5-3 we use the callback feature, which means that any time it recognizes a new song, it makes a request to a backend. We have to write a program on the backend to capture the request and save the data from the request to a database. Then serve the "what-is being-played" feed from this db. Even though it is a lot more work, I would go for option #2. We have to agree what should be the backend, my vote would be for Google or Azure cloud. This would be a nice experiment to see if it is worth move some of our stuff to the cloud. Any opinion? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by rudywaltz** [comment]
Can I ask some Update?
- do we have an account for this?
- What format need to NMHH report?

**Comment by szabidu** [comment]
an actual NMHH report: https://drive.google.com/file/d/1QaJVMGz6DCXfbQzbieAFdD1O-1RHIuqL/view

**Comment by szabidu** [comment]
No, Aggie, that is your report :)

**Comment by ant0nwax** [comment]
Whats is NMHH ?

Sent from my tard-phone.  Random auto-corrects and typos are my special
gift to you.

**Comment by rudywaltz** [comment]
NMHH is an office, all radio must send a list (monthly base?) with the played song, because of royalties. They pay for artist according to this.

**Comment by sosandris** [comment]
Are you sure, this is an actual nmhh report? It has an acrcloud id in it

szabidu <notifications@github.com> ezt írta (időpont: 2018. okt. 25., Cs
20:18):

**Comment by schaggie** [comment]
oh! wow! it doesn’t look anything like the csv I sent. also, my data was from 2017 and this shows 2018, no?
anyhow.. guess it’s just the format you added it here for. did you? 

also, i’m thinking.. ideally, the list must show apprx. 50% of Hungarian content.. I used the dj as co-author for music based programs to try and balance back than. i’m afraid this option is no longer available to get away with this requiremet. NMHH notified us officially already to make it clear: the dj cannot be named as co-author.

**Comment by sosandris** [comment]
This was not your csv, it was the doc that i downloaded from acrcloud.
If this format is acceptable to you, then you should get a login asap,
because it is readily available.
Can you use it like this?
Andris

schaggie <notifications@github.com> ezt írta (időpont: 2018. okt. 26., P
0:35):

> oh! wow! it doesn’t look anything like the csv I sent. also, my data was
> from 2017 and this shows 2018, no?
> anyhow.. guess it’s just the format you added it here for. did you?
>
> also, i’m thinking.. ideally, the list must show apprx. 50% of Hungarian
> content.. I used the dj as co-author for music based programs to try and
> balance back than. i’m afraid this option is no longer available to get
> away with this requiremet. NMHH notified us officially already to make it
> clear: the dj cannot be named as co-author.
>
> Sent from my SmartiPants
>

**Comment by schaggie** [comment]
hi Andris,

I'll have a look to double check what is required by NMHH currently in a
report and will confirm as soon as.
For now I don't think this would be much of help but is certainly a great
tool!

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Mentes
a vírusoktól. www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by ant0nwax** [comment]
thanks for clarification, what is missing for you in the acrcloud report
from 2018/07 attached by szabi?

Sent from my tard-phone.  Random auto-corrects and typos are my special
gift to you.

**Comment by szabidu** [comment]
my mistake. This is an actual report: http://raga.hu/2017-05.xlsx

**Comment by rudywaltz** [comment]
@ant0nwax this is a latest (september)   [Tilos_monitoring_log_201809 (1).xlsx](https://github.com/tilosradio/web2/files/2522187/Tilos_monitoring_log_201809.1.xlsx)

@schaggie this has enough details or what is the problem with this?

**Comment by ant0nwax** [comment]
Hi guys

@szabidu how is the progress of this tool for the webpage and maybe the stream metadata?

**Comment by schaggie** [comment]
hi! 
apologies for the delay in responding - shall be back to you on this sunject realtively soon! 
happy new year and all. 
love. Ags

**Comment by sosandris** [comment]
I set up AcrCloud to send the current song's data to my test Azure end point. You can test the output here: https://gettingstartedwithazurewebasos.azurewebsites.net/echo/
Next, I am adding a container to tilos.hu to query this end point periodically.

**Comment by ant0nwax** [comment]
Yeah, thank you Andris!!!

Sent from my P9 tard-phone running Oreo.  Random auto-corrects and typos
are my special gift to you.

**Comment by szabidu** [comment]
Ez egészen fantasztikus!!!

**Comment by sosandris** [comment]
@ant0nwax I'm still playing around with it. Today the link is https://gettingstartedwithazurewebasos.azurewebsites.net/acr.
I will change this site to return a json with the content, instead of the HTML page. Then I will move it to it's final url.
@szabidu can you create an empty git repo for me, please. No readme, no license needed. Please protect the master branch in settings. No direct push to master allowed, only with pull request. And add me to the contributors as admin. This will be the deployment git. A push to the master will automatically deploy to Azure. Thanks

**Comment by sosandris** [comment]
@ant0nwax the last song played: https://gettingstartedwithazurewebasos.azurewebsites.net/acr/last

**Comment by ant0nwax** [comment]
i thought this is final, if you change the output i will not start to do
anything, waiting for your approval to completed state.

Sent from my P9 tard-phone running Oreo.  Random auto-corrects and typos
are my special gift to you.

**Comment by szabidu** [comment]
@sosandris your repo sir: https://github.com/tilosradio/acrcloud

**Comment by ant0nwax** [comment]
If song is recognized and is still playing according to its length:

```
root@stream ~ # /home/ant0n/acrcloud_getmeta.sh
Tomáš Dvořák - Mr. Handagote - Bossa bom dia - tilos.hu
```

If song is NOT recognized because the last recognized song is already over in time, most likely because spoken word on the live radio:

```
root@stream ~ # /home/ant0n/acrcloud_getmeta.sh
Bossa bom dia - tilos.hu
```

**Comment by ant0nwax** [comment]
now the question is how to inject into the current stream, i think i found php script that can do that, because i think this is a connection to the webserver icecast2 running on stream if I think correctly...
