### ISSUE TITLE
csetcsere

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#455]
a webchat akadozva, vagy egyáltalán nem éri el az irc szervert. A Chanserv, Nickserv is állandóan kiesik.
- megoldva

**Comment by ant0nwax** [comment]
I vote for retiring IRC

**Comment by szabidu** [comment]
Me too but we have to do the hard work ASAP. What can I do?
We have chat.tilos.hu.
We have to use a minimal server for the choosen chat program. Lets vota about it!

**Comment by ant0nwax** [comment]
so I vote for rocket chat instead of irc for chat.tilos.hu, just because we use it successfully for tilos communication, I wonder why there are no other people than szabi, marci and me writing to bazis

**Comment by szabidu** [comment]
Marci voted for Riot. 
https://www.slant.co/versus/4557/20863/~irc_vs_riot
according to this list Riot is a better option: https://www.slant.co/versus/4557/20863/~irc_vs_riot

**Comment by szabidu** [comment]
itt a helye:
![chat](https://user-images.githubusercontent.com/6176225/39001442-9a1b69b2-43f6-11e8-8c8b-056993829b9c.jpg)

**Comment by ant0nwax** [comment]
according to the comparison riot vs rocketchat?

Sent from my tard-phone.  Random auto-corrects and typos are my special
gift to you.

**Comment by szabidu** [comment]
Már másik motor viszi a csetet.
