### ISSUE TITLE
Hírek érvényessége 3 nap legyen

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#456]
3 hónapja Elek Marci kijavította, hogy a feltöltött hírek érvényessége 3 nap legyen kettő helyett, de a múlt héten valahogy visszaváltozott 2 napra és így egyenként, kézzel javítják a híresek az érvényességet. Próbáltam deployolni újra a news-t, de nem sikerült a deploy, mert szabi felhasználóként nem érem el a prod könyvtárat, míg tilos felhasználóként jelszót kér tőlem. Mintha a régi kulcsot nem szeretné már :(((

**Comment by ant0nwax** [comment]
tilos@web:~/prod$ ./upgrade.sh news
2018-04-20 08:30:10 URL:https://s3-eu-west-1.amazonaws.com/tilosdeploy/service-news.jar [31259437/31259437] -> "/home/tilos/prod/jars/service-news.jar" [1]
news: stopped
news: started
service news is upgraded

**Comment by ant0nwax** [comment]
@szabidu please test

**Comment by ant0nwax** [comment]
I am not aware about this news bot, I am not a programmer, I just know that
yesterday before the french show the news have been 8 minutes?!

Sent from my tard-phone.  Random auto-corrects and typos are my special
gift to you.

**Comment by rudywaltz** [comment]
still valid bug?
