### ISSUE TITLE
nem lehet belépni a Tilos-blogokra ("redirect" gond)

### ISSUE THREAD

**Issue by djtomanek** [tilosradio/web2#462]
Akármilyen böngészővel (vagy akár telóval) próbálnék belépni a blog.tilos.hu/bossabomdia oldalon mindig újból a belépős oldalt látom az alábbi, redirect-es linken: 
http://blog.tilos.hu/bossabomdia/wp-login.php?redirect_to=http%3A%2F%2Fblog.tilos.hu%2Fbossabomdia%2Fwp-admin%2F&reauth=1 

Idén január elején már jelentkezett egyszer ugyanez a gond, akkor olyan január közepén megoldotta Elek Marci. Megköszönnénk Atesszal (http://blog.tilos.hu/hangzoirodalom), ha most is sikerülne megoldani. Köszi!

**Comment by djtomanek** [comment]
...ma már újból be tudtam lépni (és nem jelentkezett a redirect-es gond), köszi, hogyha a közbenjárásotoknak köszönhetően történt volna!

**Comment by djtomanek** [comment]
Elkiabáltam, újból jelentkezik a gond :((, újranyitottam a jegyet...

**Comment by sosandris** [comment]
Sziasztok! Segítek benne szívesen. Illetve én nem vagyok egy nagy
wordpresses, de hívok segítséget.
@Szabi saját szerveren fut a blog.tilos.hu? Kéne hozzáférés. Szombaton 1
körül megpróbálok bemenni a stúdióba stream feliratozás miatt, akkor meg
tudjuk ejteni?

szabidu <notifications@github.com> ezt írta (időpont: 2018. júl. 2., H
10:27):

**Comment by szabidu** [comment]
blog.tilos.hu Z archivenew nevű szerveren van, ami az archiv.tilos.hu-t is futtatja és az sem megy most :(
a szerver IP cme: 46.4.62.66
