### ISSUE TITLE
still somewhere http is used on the tilos.hu wordpress

### ISSUE THREAD

**Issue by ant0nwax** [tilosradio/web2#463]
please remove the http reference in links and references on wordpress
just reference / instead of http://tilos.hu/

here you see the sourcecode, and if you search for http:// you will find content inside, this needs to get removed because of security

thanks

**Comment by ant0nwax** [comment]
<!doctype html>

<html ng-app="tilosApp">




<html class="no-js"> 
<head>
    
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-P6JV724');</script>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title ng:bind-template="Tilos Rádió - {{pageTitle}}">Tilos Rádió 90,3MHz</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0 user-scalable=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="og:image" content="http://tilos.hu/images/kockalogo.png"/>
    <meta name="og:site_name" content="Tilos Rádió"/>
    <meta name="og:title" content="{{pageTitle}}"/>
    <meta name="og:description" content="{{pageDescription}}"/>
    <link rel="apple-touch-icon" href="apple-touch-icon.png">
    <link rel="apple-touch-icon" sizes="72x72" href="apple-touch-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="apple-touch-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="apple-touch-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="apple-touch-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="apple-touch-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="apple-touch-icon-152x152.png">

    <base href="/">

    <script src="//www.google.com/recaptcha/api.js?render=explicit&onload=vcRecaptchaApiLoaded" async defer></script>

    <link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.css" />
    <script src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.js"></script>
    <script>
    window.addEventListener("load", function(){
    window.cookieconsent.initialise({
      "palette": {
        "popup": {
          "background": "#000"
        },
        "button": {
          "background": "#f1d600"
        }
      },
      "content": {
        "message": "A tilos.hu sütiket használ, hogy a felhasználói élményt a végsőkig fokozza.",
        "dismiss": "Értem!",
        "link": "Részletek",
        "href": "https://tilos.hu/page/adatvedelem"
      }
    })});
    </script>
    
    
    
    
    

<link href="vendor.css?72bc7f56776210b0a1fe" rel="stylesheet"></head>
<body>

<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-P6JV724"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>

    


<div growl></div>


<div  scroll>
    <nav class="navbar navbar-default" role="navigation" ng-controller="HeaderCtrl">
        <div class="container">
            
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" ng-click="isCollapsed = !isCollapsed">
                    <span class="sr-only">Navigáció</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand visible-xs" href="/#"> Tilos&nbsp;Rádió&nbsp;90,3&nbsp;MHz</a>
            </div>

            
            <div class="navbar-collapse container" ng-show="isCollapsed">
                <ul class="nav navbar-nav" ng-click="isCollapsed = !isCollapsed">
                    <li active-link="active"><a href="/index">Főoldal</a></li>
                    <li active-link="active"><a href="/shows">Műsorok</a></li>
                    <li active-link="active"><a ng-href="/archive/{{now | date:'yyyy/MM/dd'}}">Archív</a></li>
                    <li active-link="active"><a href="/mixes/dj">Hangtár</a></li>
                    <li>
                    <li class="extra-menu">
                        <a href="#" class="dropdown-toggle extraLink" data-toggle="dropdown">Krónika</a>
                        <ul class="extra-menu-content">
                            <li active-link="active"><a href="/page/sajto-2017">Sajtó</a></li>
                            <li active-link="active"><a href="/page/maraton">Maraton</a></li>
                            <li active-link="active"><a href="/page/legendarium">Legendárium</a></li>
                            <li active-link="active"><a href="/page/memento">Mementó</a></li>
                            <li active-link="active"><a href="/page/tematikusnap">Tematikus napok</a></li>
                            <li active-link="active"><a href="/page/irasok">Írások</a></li>
                        </ul>
                    </li>
                    </li>
                    <li active-link="active" class="highlight"><a href="/page/tamogass">Támogass</a></li>
                    <li class="extra-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <div class="more-button">+</div>
                        </a>
                        <ul class="extra-menu-content">
                            <li active-link="active"><a href="/page/extra">Extra</a></li>
                            <li active-link="active"><a href="/page/info">Infó</a></li>
                            <li active-link="active"><a href="/page/elerhetoseg">Elérhetőség</a></li>
                        </ul>
                    <li active-link="active" class="englishLink"><a href="/page/english">EN</a></li>

                    </li>

                    <li class="visible-xs"><a analytics-on analytics-category="listen" analytics-event="listen_256" href="http://tilos.hu/api/v1/m3u/lastweek?stream=/tilos" target="_blank"><span>256</span>
                        mp3</a></li>
                    <li class="visible-xs"><a analytics-on analytics-category="listen" analytics-event="listen_128" href="http://tilos.hu/api/v1/m3u/lastweek?stream=/tilos_128.mp3"
                                              target="_blank"><span>128</span> mp3</a></li>
                    <li class="visible-xs"><a analytics-on analytics-category="listen" analytics-event="listen_32" href="http://tilos.hu/api/v1/m3u/lastweek?stream=/tilos_32.mp3"
                                              target="_blank"><span>32</span> mp3</a></li>
                </ul>
                <form class="navbar-form navbar-right" role="search" ng-controller="SearchBox" ng-submit="search()">
                    <div class="form-group">
                        <label for="search" class="sr-only">keresés a Tilos Rádió oldalán</label>
                        <input type="search" id="search" class="form-control" name="search" placeholder="keresés"
                               ng-model="term">
                    </div>
                    <button type="submit"><span class="icon-search"></span></button>
                </form>
            </div>
            

        </div>
        
    </nav>

    <header class="main-header hidden-xs">
        <div class="container">
            <div class="row">
                <div class="brand-holder col-sm-5 col-md-6">
                    <a href="/">
                      	<img src="/images/logo.png" alt="Tilos Rádió" class="logo">
                    </a>

                    <h1>Tilos&nbsp;Rádió&nbsp;90,3</h1>

                    <h5>
                      <a href="http://tilos.hu/page/faq">
                        <img src="https://tilos.hu/images/header-icons-faq.png">
                        <span class="header">FAQ</span>
                      </a>
                  	</h5>

                </div>
                <div class="col-sm-offset-1 col-md-offset-0 col-sm-6 col-md-6 radio-holder">
                    <div class="radio-player">
                        <div class="col-sm-12 col-md-6 radio-info">
                            <h3>
                                <current-show></current-show>
                            </h3>
                        </div>
                        <div class="col-sm-12 col-md-6 radio-formatList">
                            <h4>HALLGASD ONLINE!<span class="active icon-loop"></span></h4>
                            <ul class="stream-chooser">

                                <li><a href="http://tilos.hu/api/v1/m3u/lastweek?stream=/tilos" target="_blank"><span>256</span> mp3</a>
                                </li>
                                <li><a href="http://tilos.hu/api/v1/m3u/lastweek?stream=/tilos_128.mp3" target="_blank"><span>128</span>
                                    mp3</a></li>
                                <li><a href="http://tilos.hu/api/v1/m3u/lastweek?stream=/tilos_32.mp3" target="_blank"><span>32</span>
                                    mp3</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            
        </div>
        
    </header>
</div>



        
        
    
    <div id="maraton" ng-controller="MaratonCtrl">
        <center>
        <div id="donation--indicator--wrapper">
            <div id="title">
            <span><b>MARATON</b></span><br>
            <span>ADOMÁNY<br></span>
            <span>MUTATÓ<br></span>
            <span id="income-box">MONEY</span>
            </div>
                 <div id="donation--indicator--container">
                    <div class="ico-wifi"></div>
                    <div id="progress"></div>
                    <div id="axis"></div>
                </div>
            </div>
        </center>
    </div> 
    
<main class="container" id="mainIndex">

    <ui-view></ui-view>

</main>



<div class="footer-holder">
    <footer class="container">
        <div class="row">
            <div class="col-md-4">
                <nav class="footer-nav">
                </nav>
                <h2>A Tilos Rádió elérhetőségei</h2>

                <p>adástelefon: 215 3773</p>

                <p>e-mail: <a href="mailto:radio@tilos.hu">radio@tilos.hu</a></p>
                
                <p>A weboldallal kapcsolatos kérdésekben az illetékes: <a href="mailto:webmester@tilos.hu">webmester@tilos.hu</a>
                </p>
                
                <p>Hírt, eseményt, ajánlót ide küldj: <a href="mailto:hirek@tilos.hu">hirek@tilos.hu</a></p>
                
                <p>Zenei ajánlót, dalt, mixet ide küldj: <a href="mailto:zene@tilos.hu">zene@tilos.hu</a></p>
                
                <p>Ha szeretnél olyan tematikájú műsort indítani, ami még nincs a Tilosban, akkor szerkesztőségének írj: <a
                        href="mailto:szerkesztoseg@tilos.hu">szerkesztoseg@tilos.hu</a></p>

            </div>
            <div class="col-md-4">
                <h2>A Tilos Rádiót működtető Tilos Kulturális Alapítvány elérhetőségei:</h2>

                <p>
                    A Tilos Rádió egy non-profit közösségi rádió. <br/>
                    Adástelefon: (+361) 2153773<br/>
                    Frekvencia: 90.3Mhz<br/>
                    1085 Budapest, Mária u. 54.<br/>
                    telefon: (+361) 476 8491<br/>
                    fax: (+361) 476 8492<br/>
                    <a href="mailto:radio@tilos.hu">radio@tilos.hu</a><br/>
                    postacím: 1462 Budapest, Pf. 601.<br/><br/>
                    <a href="https://tilos.hu/page/alapitvany">Tilos Kulturális Alapítvány info</a><br/>
                    adószám: 18002452-2-42
                </p>
            </div>
            <div class="col-md-4">
                <h2>A Tilos Kulturális Alapítvány első és alapvető tevékenysége a Tilos Rádió működtetése.</h2>

                <p>
                    A folyamatos, huszonnégy órás, élő műsorokat közvetítő rádió működését közel 380 önkéntes műsorkészítő és mintegy 150 munkatárs önzetlen munkája teszi lehetővé. A Tilos interaktív műsorfolyama civil küldetést teljesít: alternatív művészeti értékeket mutat meg, ösztönzi a társadalmi szolidaritást, küzd a diszkrimináció ellen, harcol az emberi szabadságjogokért.<br>A <a href="https://tilos.hu/page/alapitvany">Tilos Kulturális Alapítvány</a> demokráciát épít. 
                </p>
                <p>
                 <a href="https://www.acrcloud.com/broadcast-monitoring">Radio airplay monitoring</a> is powered by <a href="https://www.acrcloud.com/">ACRCloud</a>    
                </p>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <p>© 2018. Tilos Rádió -- Minden jog fenntartva<br/>
                <a href="https://tilos.hu/page/adatvedelem">adatvédelmi tájékoztató</a></p>
            </div>
        </div>
    </footer>
</div>

	
    
<script>
    (function (b, o, i, l, e, r) {
        b.GoogleAnalyticsObject = l;
        b[l] || (b[l] =
                function () {
                    (b[l].q = b[l].q || []).push(arguments)
                });
        b[l].l = +new Date;
        e = o.createElement(i);
        r = o.getElementsByTagName(i)[0];
        e.src = '//www.google-analytics.com/analytics.js';
        r.parentNode.insertBefore(e, r)
    }(window, document, 'script', 'ga'));
    ga('create', 'UA-1346207-1');
</script>

<script>(function() {
  var _fbq = window._fbq || (window._fbq = []);
  if (!_fbq.loaded) {
    var fbds = document.createElement('script');
    fbds.async = true;
    fbds.src = '//connect.facebook.net/en_US/fbds.js';
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(fbds, s);
    _fbq.loaded = true;
  }
  _fbq.push(['addPixelId', '1511345089080647']);
})();
window._fbq = window._fbq || [];
window._fbq.push(['track', 'PixelInitialized', {}]);
</script>
<noscript><img height="1" width="1" alt="" style="display:none" src="https://www.facebook.com/tr?id=1511345089080647&amp;ev=PixelInitialized" /></noscript>

<script src="vendor.bundle.js?72bc7f56776210b0a1fe"></script><script src="main.bundle.js?72bc7f56776210b0a1fe"></script></body>
</html>

**Comment by szabidu** [comment]
I think all http is removed. Only raga.hu and stream.tilos.hu remained, but both are http and not https

**Comment by ant0nwax** [comment]
you did not search for http:// in the sourcecode that I posted, please take it more serious, thanks

**Comment by szabidu** [comment]
ok, if you search the website instead of the particular elements you could fiónd amazing things...
I have checked this: https://github.com/tilosradio/web2-frontend/blob/master/client/main/index.html
and this: https://github.com/tilosradio/web2-frontend/blob/master/app/index.html
Is there anything else I can do for you?

**Comment by szabidu** [comment]
I have just upgraded the frontend, so all the changings are there. I can check if ther is any mistake in the morning.

**Comment by ant0nwax** [comment]
![tilos hu_http](https://user-images.githubusercontent.com/33480652/42207620-a6c5a2d8-7eaa-11e8-8bca-a25768be4735.png)

**Comment by szabidu** [comment]
Can you help me to find those sneaky http, please!

**Comment by ant0nwax** [comment]
the source view that I showed is your friend, search in it for http and
rethink how those links got into the page, I wrote the links to images
should be starting at / and not at http://(www).tilos.hu/

Sent from my tard-phone.  Random auto-corrects and typos are my special
gift to you.

**Comment by szabidu** [comment]
But there is no active http link in thta anymore. Only as comment.

**Comment by GreenDogh** [comment]
maybe this plugin is useful:

https://hu.wordpress.org/plugins/really-simple-ssl/


2018. 07. 03. 20:07 keltezéssel, szabidu írta:

**Comment by ant0nwax** [comment]
please be careful with that, we have a custom webpage

Sent from my tard-phone.  Random auto-corrects and typos are my special
gift to you.

**Comment by rudywaltz** [comment]
I do not see any cert error. please reopen if found somewhere.
