### ISSUE TITLE
archive.tilos.hu is down 

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#465]
archive.tilos.hu is down, so there is no working archive at all 😞

😞 I have checked the payment. It is ok. Is there any other idea? 

https://archive.tilos.hu/online/2018/07/02/

**Comment by ant0nwax** [comment]
ant0n@digital:~$ ping archive.tilos.hu
PING archive.tilos.hu (46.4.62.66) 56(84) bytes of data.
^C
--- archive.tilos.hu ping statistics ---
3 packets transmitted, 0 received, 100% packet loss, time 1999ms

@elek please correct the login details to the cloud provider, I cannot access the account for reaching teh console, thanks
