### ISSUE TITLE
Facebook Title és pageDescription PARA

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#467]
Megint nem látszanak ezek a fontos infók, így elég szegényes a tilos oldalról a facera posztolni.
![unnamed](https://user-images.githubusercontent.com/6176225/42579081-cac08256-8527-11e8-9406-de817c947be5.png)

Any solution?

**Comment by rudywaltz** [comment]
We need server-side rendering for a robot. I think it's worked before, but I'm not sure, maybe @szabidu  remember, he shares ever any link on facebook with correct "design".

**Comment by szabidu** [comment]
It worked before July (I have found a post of 3. utas from 3rd of April where even a picture was in the post autonaticly)
![nevtelen-1](https://user-images.githubusercontent.com/6176225/47136010-a17aee80-d2b2-11e8-8bf6-f06915446582.jpg)

**Comment by rudywaltz** [comment]
Close because of  #474
