### ISSUE TITLE
nem aktív műsorok

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#472]
A műsorok besorolásánál van AKTIV és LEGENDA besorolás. Azok a műsorok, amiknek már nincs adásideje, mennek a legenda besorolásba. 

Nagyon menő lenne 2 fül ezen az oldalon https://tilos.hu/shows : 
AKTIV  LEGENDA

Az lenne a menő, ha az oldalon automatikusan az aktív műsorok fül nyílna meg, alatta az aktív műsorok felsorolásával, de a LEGENDA fülre kattintva a korábbi, már nem aktív műsorokat is lehetne böngészni.

**Comment by rudywaltz** [comment]
én csak aktív státuszú műsort látok azon az oldalon, tudsz mondani egy példát?

**Comment by rudywaltz** [comment]
nevermind, megtaláltam hogy lehet előcsalogatni az endpointot

**Comment by szabidu** [comment]
Azért itt egy példa: https://tilos.hu/show/honthy-es-hanna ;)

**Comment by rudywaltz** [comment]
Műsort tudtam én is behozni, de a műsorok listában nem szerepeltem. Kell
meg kis extra hozza h használható legyen, de úton van...

szabidu <notifications@github.com> ezt írta (időpont: 2018. nov. 1., Cs
19:13):

**Comment by rudywaltz** [comment]
in production
