### ISSUE TITLE
legenda műsorok hallgatása

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#473]
Ha elkészül a https://github.com/tilosradio/web2/issues/472 szerinti műsoroldal a következő nagy dobás az lehetne, hogy a már nem aktív (legenda) műsorokra kattintva meg lehetne hallgatni a régebbi adásaikat. Jelenleg ennek az az akadálya, hogy az aktuális naphoz viszonyítja a műsor nyitóoldalát, AZAZ, ha egy legenda műsor hetente jelentkezett, de már egy éve nem aktív, akkor 12 üres oldalt kéne visszalapozni, hogy eljussunk a legutolsó meghallgatható adásaikig. Viszont, ha egy műsor legenda besorolást kap, akkor az lenne a tökéletes, hogy a rendszer megvizsgálja, mikor volt az adás utoljára és ahhoz képest rakná ki az utolsó adásait.

**Comment by szabidu** [comment]
Itt gey példaműsor: https://tilos.hu/show/honthy-es-hanna

**Comment by rudywaltz** [comment]
in production
