### ISSUE TITLE
TIMEWARP!!! Súlyos időcsúszás az archívumban

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#483]
Itt egy példa a szerver időzavarára:
Amikor megnyitom ezt a fájlt, akkor 10:07:25-kor kezdődik benne a 3. utas:
https://archive.tilos.hu/cache/tilos-20190821-100000-120000.mp3

Viszont amikor az adminban ezt a 10:07:25 számot megadom kezdésnek, akkor már egy ideje megy az adás:
https://archive.tilos.hu/cache/tilos-20190821-100725-120000.mp3

És akkor elkezdek találgatni, mikor volt a kezdés a szerver (?) szerint, 6. találatra meg is lett:
https://archive.tilos.hu/cache/tilos-20190821-100533-120000.mp3 

Úgy tűnik, de talán véletlen egybeesés, hogy a költözéssel egy időben történt valami, de úgy, hogy azóta a fél órás részek közötti átfedés is belekerült az egyes archív adásokba.

**Comment by szabidu** [comment]
Elértem, Elek Marcit és TÉNYLEG a 192/256 váltás okozza az archív parát!!!! Illetve a 256-nak VBRnek kell lennie! Utána minden kisimul!

**Comment by elek** [comment]
Sima ez.

https://archive.tilos.hu/cache/tilos-20190821-100725-120000.mp3
