### ISSUE TITLE
csakegyfoldunkvan.tilos.hu

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#484]
need a docker container: csakegyfoldunkvan.tilos.hu
So this site could migrate to tilos server: http://csakegyfoldunkvan.hu/

**Comment by ant0nwax** [comment]
the A record in DNS was generated

**Comment by szabidu** [comment]
Do I have an access?

**Comment by ant0nwax** [comment]
I cannot make docker container

**Comment by szabidu** [comment]
oh so! Who can?

**Comment by ant0nwax** [comment]
i remember Abel and mikl made a moving of chat possible, maybe

Sent from my P9 tard-phone running Oreo.  Random auto-corrects and typos
are my special gift to you.

**Comment by ant0nwax** [comment]
csakegyfoldunkvan.tilos.hu hosts the static webpage now, if you would like to forward to four number ip then use the ip of archive.tilos.hu (ping it) maybe it will work

**Comment by szabidu** [comment]
Sajnos az egész projektet lefújta a tilos csapat :(
