### ISSUE TITLE
news service

### ISSUE THREAD

**Issue by ant0nwax** [tilosradio/web2#485]
Hi Andris

last time you fixed something in the news
there is another issue that exists since years, according to a tech guy

When the Robot generates the different news and put them to a folder like on the screenshot it generates WAV files and names them mp3, that is causing trouble for years :)

could you try to find the code where the content of the screenshot is generated and add a simple rename from $filename".mp3" to $filename".wav" ?

![image](https://user-images.githubusercontent.com/33480652/64065013-a44fab00-cc08-11e9-8e2c-437af22d43b1.png)

**Comment by ant0nwax** [comment]
assigned @sosandris 

please check, thanks

**Comment by szabidu** [comment]
Működik a wav kiterjesztés! Köszi a segítséget!
