### ISSUE TITLE
hírek before para

### ISSUE THREAD

**Issue by szabidu** [tilosradio/web2#486]
Bármit bemásolok a before mappába (zöld hírek, illetve most menne a szülinap kampány), akkor lehal a news rendszer. 

Ez egy friss hiba, mert augusztus 31-én még működött a Zöld Kampányunk.

**Comment by sosandris** [comment]
Volt eg commit aug 25-én. Nem lehet, hogy az lett élestve tegnap?
@szabidu mi lenne, ha újra deploy-olnánk a News service egy korábbi, még működő verzióját? Valami más elromlana?

**Comment by szabidu** [comment]
25-én a pénteki nap beosztását alakítottuk át és pénteken jól is működött. Valami szombaton történt...
