### ISSUE TITLE
Mix archívum filenév problémák

### ISSUE THREAD

**Issue by intonarumori** [tilosradio/web2#488]
A mixek közül az alábbiak szóközt tartalmaznak a névben, emiatt az API-ban nem valid url-ek kerülnek beágyazásra:

https://archive.tilos.hu/sounds/mixek/Tilos_Selection_vol_16-nizar_wiener_schnitzel special-1406014.mp3
https://archive.tilos.hu/sounds/mixek/popdavec_beat the dead horse back to life_optimal_2018-06-22_pt2.mp3
https://archive.tilos.hu/sounds/mixek/popdavec_there are other worlds_optimal_2018-06-22_pt3.mp3

Továbbá az alábbi mixek ékezeteket tartalmaznak, mivel az api-ban probléma van a karakterkódolással (#489), ezek is nem valid url-ként kerülnek az api-ban:

https://archive.tilos.hu/sounds/musorok/3.utas-MolnÃ¡r-Attila-David-termeszetfilmes-160921.mp3
https://archive.tilos.hu/sounds/mixek/popdavec_hullÃ¡mos_optimal_2016-08-29_pt1.mp3

Javasolnám:
- API-ban url encodolása, hogy a JSON-ban már valid linkek legyenek
- filenevek és adatbázisban található link frissítése a szóközök alulvonásra, ékezetek sima karakterre cseréje

**Comment by intonarumori** [comment]
@szabidu ezekre tudsz mondani valamit, esetleg admin oldalon helyre tudjuk rakni a problémás eseteket most?

**Comment by szabidu** [comment]
HA csak ennyi van, akkor kézzel rendbeteszem ;)

**Comment by szabidu** [comment]
Mindet javítottam
