### ISSUE TITLE
Ismétlődő elemek a Műsorok archívumban

### ISSUE THREAD

**Issue by intonarumori** [tilosradio/web2#491]
A műsorok között találtam olyan ami többszörösen kerül listázásra.
Lehet valami importálási/editálási probléma eredménye?

<img width="897" alt="Screenshot 2021-03-26 at 14 37 33" src="https://user-images.githubusercontent.com/86030/112639911-1ae27800-8e41-11eb-8873-08f13bfce97e.png">

Akár manuálisan is, de érdemes lenne kicsit rendet rakni. @szabidu ?

**Comment by szabidu** [comment]
megoldom kézzel

**Comment by szabidu** [comment]
kész
